import pytz

# All Jibble timestamps are treated as IST — the Jibble account is configured in IST.
# If probe output shows UTC timestamps, set JIBBLE_TIMESTAMPS_UTC = True in .env.
IST = pytz.timezone("Asia/Kolkata")

WORK_WINDOW_START_HOUR = 11    # 11:00 AM IST — full-timers only
EXCESSIVE_HOURS_THRESHOLD = 10  # hours/day before flagging
EXCESSIVE_SESSIONS_THRESHOLD = 4  # clock-in/clock-out pairs before flagging
AT_RISK_BUFFER_HRS = 4          # hours below effective target → "At Risk" (not "Deficit")

# Employee roster — keyed by Jibble name (exact string from /v1/people response).
# member_id: fill in the values after running: python main.py --probe
# The engine uses memberId as primary key once synced to Supabase.
EMPLOYEES = {
    "Bhat Aasim": {
        "display_name": "Aasim",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Abdul Muksith A": {
        "display_name": "Muksith",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Abhishek Kumar": {
        "display_name": "Abhishek",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Abhishek Bhardwaj": {
        "display_name": "Abhishek B",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Abhishek Kalivela": {
        "display_name": "Abhishek (Frontend)",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Arfath Tade": {
        "display_name": "Arfath",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Gopi S": {
        "display_name": "Gopi",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Ishwar Singh": {
        "display_name": "Ishwar",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Kannan Ravindran": {
        "display_name": "Kannan",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Prathmesh Gaidhane": {
        "display_name": "Prathmesh",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Rajat Chugh": {
        "display_name": "Rajat",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Samiksha Patil": {
        "display_name": "Samiksha",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Shaik Shahbaaz Alam": {
        "display_name": "Shahbaaz",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Shuvam Jaswal": {
        "display_name": "Shuvam",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 40,
        "daily_target_hrs": 8,
        "time_window_rules": True,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Anum Basit": {
        "display_name": "Anum",
        "member_id": None,
        "employment_type": "part_time",
        "weekly_target_hrs": 20,
        "daily_target_hrs": 4,
        "time_window_rules": False,
        "timezone": "Asia/Kolkata",  # Jibble account shows Dubai employee in IST
        "is_excluded": False,
    },
    "Ubaid Syed": {
        "display_name": "Ubaid",
        "member_id": None,
        "employment_type": "part_time",
        "weekly_target_hrs": 20,
        "daily_target_hrs": 4,
        "time_window_rules": False,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
    },
    "Richa Jindal": {
        "display_name": "Richa",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 0,
        "daily_target_hrs": 0,
        "time_window_rules": False,
        "timezone": "Asia/Kolkata",
        "is_excluded": False,
        "is_active": False,
    },
    "Faizan Shaikh": {
        "display_name": "Faizan",
        "member_id": None,
        "employment_type": "full_time",
        "weekly_target_hrs": 0,
        "daily_target_hrs": 0,
        "time_window_rules": False,
        "timezone": "Asia/Kolkata",
        "is_excluded": True,
    },
}
