"""
Attendance Dashboard — Streamlit web app.
Run: streamlit run dashboard.py
"""

import calendar
import os
from datetime import date, timedelta

import pandas as pd
import streamlit as st
from dotenv import load_dotenv
from supabase import create_client

load_dotenv()


def _secret(key: str) -> str:
    try:
        return st.secrets[key]
    except (KeyError, FileNotFoundError):
        return os.environ[key]


st.set_page_config(
    page_title="Attendance Dashboard",
    page_icon="📋",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

st.markdown("""
<style>
footer { visibility: hidden; }

/* Hide sidebar entirely */
section[data-testid="stSidebar"]          { display: none !important; }
button[data-testid="collapsedControl"]    { display: none !important; }
button[data-testid="baseButton-headerNoPadding"] { display: none !important; }

/* Metric cards */
[data-testid="metric-container"] {
    background: rgba(255,255,255,0.06);
    border-radius: 10px;
    border: 1px solid rgba(255,255,255,0.12);
    padding: 1rem 1.25rem;
}
[data-testid="stMetricLabel"] {
    font-size: 0.78rem !important;
    font-weight: 600 !important;
    text-transform: uppercase;
    letter-spacing: .05em;
    opacity: 0.7;
}

/* Tabs */
.stTabs [data-baseweb="tab-list"] {
    background: transparent;
    border-bottom: 2px solid rgba(255,255,255,0.12);
    gap: 0;
    padding-bottom: 0;
}
.stTabs [data-baseweb="tab"] {
    padding: 10px 28px;
    font-size: 0.9rem;
    font-weight: 500;
    border-bottom: 3px solid transparent;
    margin-bottom: -2px;
    background: transparent !important;
}
.stTabs [aria-selected="true"] {
    border-bottom: 3px solid #60a5fa !important;
    font-weight: 700 !important;
}
.stTabs [data-baseweb="tab-highlight"] { display: none !important; }

/* Alert banners */
.alert {
    border-radius: 8px;
    padding: 10px 16px;
    margin-bottom: 8px;
    font-size: 0.88rem;
    font-weight: 500;
    line-height: 1.5;
}
.alert-red    { background: rgba(239,68,68,0.15);  border-left: 4px solid #f87171; color: #fca5a5; }
.alert-yellow { background: rgba(245,158,11,0.15); border-left: 4px solid #fbbf24; color: #fcd34d; }
.alert-blue   { background: rgba(96,165,250,0.15); border-left: 4px solid #60a5fa; color: #93c5fd; }
.alert-green  { background: rgba(34,197,94,0.15);  border-left: 4px solid #4ade80; color: #86efac; }

/* Date badge */
.date-badge {
    display: inline-block;
    background: rgba(96,165,250,0.15);
    border: 1px solid rgba(96,165,250,0.3);
    border-radius: 6px;
    padding: 4px 12px;
    font-size: 0.82rem;
    color: #93c5fd;
    font-weight: 600;
}

/* Prev / Next nav buttons — compact */
.nav-row button {
    padding: 4px 14px !important;
    font-size: 0.82rem !important;
}

/* Segmented control full width */
[data-testid="stSegmentedControl"] { width: 100%; }
[data-testid="stSegmentedControl"] > div { flex-wrap: wrap; gap: 4px; }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# Supabase client
# ---------------------------------------------------------------------------

@st.cache_resource
def get_supabase():
    return create_client(_secret("SUPABASE_URL"), _secret("SUPABASE_SERVICE_KEY"))

sb = get_supabase()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PRESETS = ["Today", "Yesterday", "This Week", "Last Week", "This Month", "Last Month", "This Year", "Custom"]

ANOMALY_SEVERITY = {
    "Unexcused Absence":    1,
    "Consecutive Absence":  2,
    "Weekly Deficit":       3,
    "Chronic Late Starter": 4,
    "Missing Clock-Out":    5,
    "Late / No Start":      6,
    "Long Breaks":          7,
    "Excessive Hours":      8,
}
_CRITICAL = {"Unexcused Absence", "Consecutive Absence", "Weekly Deficit"}
_WARNING  = {"Chronic Late Starter", "Missing Clock-Out", "Late / No Start"}

# Anomaly types no longer generated by the engine.  Historical rows of these
# types are filtered out of the dashboard so they don't distract managers.
HIDDEN_ANOMALY_TYPES = {"Excessive Breaks", "Early Departure"}

# Leave types that are company-wide non-working days (public holidays), not
# personal leave.  They still reduce expected/target hours (nobody is expected
# to work), but must NOT be tallied in the "Leave Days" columns or the
# "On leave" alerts — counting them made April show 3 leaves when only 2 were
# actual personal leave.
HOLIDAY_LEAVE_TYPES = {"Public Holiday"}

# ---------------------------------------------------------------------------
# Range helpers
# ---------------------------------------------------------------------------

def _compute_range(option: str, offset: int, today: date) -> tuple[date, date, str]:
    """Return (start, end, granularity) for a preset + integer offset."""
    if option in ("Today", "Yesterday"):
        base = today if option == "Today" else today - timedelta(days=1)
        d = min(base + timedelta(days=offset), today)
        return d, d, "day"

    if option in ("This Week", "Last Week"):
        this_monday = today - timedelta(days=today.weekday())
        base_monday = this_monday if option == "This Week" else this_monday - timedelta(days=7)
        monday = base_monday + timedelta(weeks=offset)
        # Mon–Sun, not Mon–Fri: weekend catch-up hours belong to the week they
        # were worked in. Targets stay Mon–Fri (see _working_days_active).
        sunday = monday + timedelta(days=6)
        return monday, min(sunday, today), "week"

    if option in ("This Month", "Last Month"):
        if option == "Last Month":
            first_this = date(today.year, today.month, 1)
            prev       = first_this - timedelta(days=1)
            base_year, base_month = prev.year, prev.month
        else:
            base_year, base_month = today.year, today.month
        total = base_year * 12 + (base_month - 1) + offset
        year  = total // 12
        month = total % 12 + 1
        start = date(year, month, 1)
        last_day = calendar.monthrange(year, month)[1]
        return start, min(date(year, month, last_day), today), "month"

    if option == "This Year":
        year = today.year + offset
        return date(year, 1, 1), min(date(year, 12, 31), today), "month"

    return today, today, "day"


def _range_label(start: date, end: date, gran: str) -> str:
    if gran == "day":
        return start.strftime("%A, %d %b %Y")
    if gran == "week":
        return f"Week of {start.strftime('%d %b')} – {end.strftime('%d %b %Y')}"
    if start.month == end.month and start.year == end.year:
        return start.strftime("%B %Y")
    return f"{start.strftime('%d %b %Y')} – {end.strftime('%d %b %Y')}"


def _date_badge(start: str, end: str) -> str:
    return f'<span class="date-badge">📅 {start} → {end}</span>'


# ---------------------------------------------------------------------------
# Range picker widget  (one instance per tab, keyed by prefix)
# ---------------------------------------------------------------------------

def range_picker(prefix: str) -> tuple[str, str, str]:
    """
    Renders: segmented control → [◀  date badge  ▶] or custom date pickers.
    Returns (start_str, end_str, granularity) where granularity ∈ {day, week, month}.
    """
    today = _today()

    seg_key  = f"{prefix}_seg"
    off_key  = f"{prefix}_off"
    prev_key = f"{prefix}_prev_opt"

    # Initialise session state on first render
    if seg_key not in st.session_state:
        st.session_state[seg_key]  = "This Week"
        st.session_state[off_key]  = 0
        st.session_state[prev_key] = "This Week"

    # Segmented control — value lives in st.session_state[seg_key]
    st.segmented_control(
        "Date range",
        PRESETS,
        key=seg_key,
        label_visibility="collapsed",
    )
    option = st.session_state[seg_key]

    # Reset offset whenever user switches to a different preset
    if option != st.session_state[prev_key]:
        st.session_state[off_key]  = 0
        st.session_state[prev_key] = option

    # ── Custom ───────────────────────────────────────────────────────────────
    if option == "Custom":
        c1, c2 = st.columns(2)
        cs = c1.date_input("From", value=today - timedelta(days=30), max_value=today, key=f"{prefix}_cs")
        ce = c2.date_input("To",   value=today - timedelta(days=1),  max_value=today, key=f"{prefix}_ce")
        if cs > ce:
            st.error("'From' must be before 'To'.")
            st.stop()
        gran = "day" if cs == ce else "month"
        return cs.isoformat(), ce.isoformat(), gran

    # ── Preset with Prev / Next ───────────────────────────────────────────────
    offset          = st.session_state[off_key]
    start, end, gran = _compute_range(option, offset, today)
    can_next        = end < today

    prev_col, badge_col, next_col = st.columns([1, 10, 1])

    with prev_col:
        if st.button("◀", key=f"{prefix}_prev", use_container_width=True):
            st.session_state[off_key] -= 1
            st.rerun()

    with badge_col:
        label = _range_label(start, end, gran)
        st.markdown(
            f'<div style="text-align:center;padding:6px 0 2px;">'
            f'{_date_badge(start.isoformat(), end.isoformat())}'
            f'<br><span style="font-size:0.75rem;opacity:0.55;">{label}</span>'
            f'</div>',
            unsafe_allow_html=True,
        )

    with next_col:
        if st.button("▶", key=f"{prefix}_next", use_container_width=True, disabled=not can_next):
            st.session_state[off_key] += 1
            st.rerun()

    return start.isoformat(), end.isoformat(), gran


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _today() -> date:
    """Current date in IST. The server may run in UTC (Streamlit Cloud), where
    date.today() is a day behind IST between midnight and 5:30 AM."""
    return pd.Timestamp.now(tz="Asia/Kolkata").date()


def _display_names(emp: pd.DataFrame) -> pd.Series:
    """Short display name per employee, falling back to the full Jibble name."""
    if "display_name" in emp.columns:
        return emp["display_name"].fillna(emp["jibble_name"])
    return emp["jibble_name"]


def _flatten_employees(df: pd.DataFrame):
    emp = pd.json_normalize(df["employees"])
    df  = df.drop(columns=["employees"])
    df["Employee"] = _display_names(emp)
    df["Type"]     = emp["employment_type"].str.replace("_", " ").str.title()
    return df, emp


def _parse_date(val):
    """Parse a Supabase date value to a python date object, or None."""
    if val is None:
        return None
    try:
        if pd.isna(val):
            return None
    except (TypeError, ValueError):
        pass
    try:
        return date.fromisoformat(str(val)[:10])
    except (ValueError, TypeError):
        return None


def _filter_active_on(df: pd.DataFrame, snap_date_col: str = "snapshot_date") -> pd.DataFrame:
    """
    Drop rows where the snapshot_date is outside the employee's
    [joined_date, departed_date] active range.  Caller must have already
    flattened employees() and have _joined / _departed columns.
    """
    if df.empty or "_joined" not in df.columns:
        return df
    snap_dates = pd.to_datetime(df[snap_date_col]).dt.date
    join_ok    = df["_joined"].isna()    | (snap_dates >= df["_joined"])
    depart_ok  = df["_departed"].isna()  | (snap_dates <= df["_departed"])
    return df[join_ok & depart_ok].copy()


def _working_days_active(monday: date, friday: date, joined, departed) -> int:
    """Count Mon-Fri days in [monday, friday] within the employee's active range."""
    return sum(
        1 for i in range(5)
        if (joined is None or monday + timedelta(days=i) >= joined)
        and (departed is None or monday + timedelta(days=i) <= departed)
    )


def _fmt_hrs(h) -> str:
    try:
        h = float(h)
    except (TypeError, ValueError):
        return "—"
    if pd.isna(h):
        return "—"
    total_min = round(abs(h) * 60)
    return f"{total_min // 60}h {total_min % 60}m"


def _fmt_hrs_signed(h) -> str:
    """Signed variant of _fmt_hrs for net (±) values, e.g. '+3h 20m' / '−1h 05m'."""
    try:
        h = float(h)
    except (TypeError, ValueError):
        return "—"
    if pd.isna(h):
        return "—"
    sign = "−" if h < 0 else "+"
    total_min = round(abs(h) * 60)
    return f"{sign}{total_min // 60}h {total_min % 60}m"


def _parse_utc(val) -> "pd.Timestamp":
    """Parse a raw Supabase timestamptz value to a UTC-aware Timestamp, or NaT.

    Using the scalar pd.to_datetime path is intentional: the vectorised
    pd.to_datetime(series, utc=True) can silently coerce valid timezone-aware
    strings to NaT on some pandas builds when the column contains a mix of
    timezone-aware strings and None values.
    """
    if val is None:
        return pd.NaT
    try:
        if pd.isna(val):
            return pd.NaT
    except (TypeError, ValueError):
        pass
    return pd.to_datetime(val, utc=True, errors="coerce")


def _to_ist_str(val) -> str:
    """Convert a raw timestamptz value to an IST HH:MM AM/PM string, or '—'."""
    ts = _parse_utc(val)
    if pd.isna(ts):
        return "—"
    return ts.tz_convert("Asia/Kolkata").strftime("%I:%M %p")


def _fmt_map(df: pd.DataFrame, mapping: dict) -> dict:
    """Drop formatters for absent columns — optional ones like 'Weekend Hrs'
    only appear in ranges where somebody actually worked a weekend."""
    return {k: v for k, v in mapping.items() if k in df.columns}


def _style_weekend(styled, df: pd.DataFrame):
    """Tint the optional Weekend Hrs column when it is present."""
    if "Weekend Hrs" in df.columns:
        return styled.map(_color_weekend, subset=["Weekend Hrs"])
    return styled


def _csv_button(df: pd.DataFrame, filename: str, key: str):
    """Render a 'Export CSV' download button for the given DataFrame."""
    if df is None or df.empty:
        return
    csv = df.to_csv(index=False).encode("utf-8")
    st.download_button(
        "📥 Export CSV",
        data=csv,
        file_name=filename,
        mime="text/csv",
        key=key,
    )


# ---------------------------------------------------------------------------
# Data loaders
# ---------------------------------------------------------------------------

# PostgREST (Supabase) caps every response at 1000 rows by default.  Range
# queries that span more than ~2.5 months exceed that at current headcount, so a
# bare .execute() silently drops rows and under-counts everything (this is what
# made a Jan–Jun range show fewer leaves than April alone).  _fetch_all pages
# through the full result set so summaries are computed on complete data.
_PAGE_SIZE = 1000

def _fetch_all(build_query) -> list[dict]:
    """Return every row for a Supabase query, paging past the 1000-row API cap.

    `build_query` is a zero-arg callable returning a fresh query (select +
    filters + a stable .order()), WITHOUT range/limit applied.
    """
    rows: list[dict] = []
    offset = 0
    while True:
        batch = build_query().range(offset, offset + _PAGE_SIZE - 1).execute().data or []
        rows.extend(batch)
        if len(batch) < _PAGE_SIZE:
            return rows
        offset += _PAGE_SIZE


@st.cache_data(ttl=60)
def load_last_synced() -> str | None:
    """ISO timestamp of the most-recent engine run (global max pulled_at).
    Formatting and staleness are computed by the header so they always use the
    current clock rather than the cached value's age.
    """
    res = (
        sb.table("daily_snapshots")
        .select("pulled_at")
        .order("pulled_at", desc=True)
        .limit(1)
        .execute()
    )
    if not res.data:
        return None
    ts = _parse_utc(res.data[0].get("pulled_at"))
    return ts.isoformat() if pd.notna(ts) else None


@st.cache_data(ttl=60)
def load_daily_snapshot(snap_date: str) -> pd.DataFrame:
    """Returns formatted attendance DataFrame for snap_date."""
    rows = (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, session_count, first_clock_in, last_clock_out, leave_type, pulled_at, "
                "employees(jibble_name, display_name, employment_type, daily_target_hrs, joined_date, departed_date)")
        .eq("snapshot_date", snap_date)
        .execute()
    )
    df = pd.DataFrame(rows.data)
    if df.empty:
        return df

    df, emp_raw = _flatten_employees(df)
    df["_daily_target"] = emp_raw["daily_target_hrs"].astype(float)
    df["_joined"]   = emp_raw["joined_date"].map(_parse_date)
    df["_departed"] = emp_raw["departed_date"].map(_parse_date)
    df = _filter_active_on(df)
    df = df.drop(columns=["_joined", "_departed"])
    if df.empty:
        return df

    # Parse timestamps element-by-element via the scalar path.
    # pd.to_datetime(series, utc=True) can silently coerce valid timezone-aware
    # strings to NaT when the column also contains None values on some pandas
    # versions, so we map the scalar helper across the column instead.
    first_ts = df["first_clock_in"].map(_parse_utc)   # object Series: Timestamps + NaT
    last_ts  = df["last_clock_out"].map(_parse_utc)

    # Break Hrs: span(clock-out − clock-in) minus worked hours
    def _span(fi, lo):
        if pd.isna(fi) or pd.isna(lo):
            return float("nan")
        return (lo - fi).total_seconds() / 3600

    span_hrs = pd.Series(
        [_span(fi, lo) for fi, lo in zip(first_ts, last_ts)], index=df.index
    )
    df["Break Hrs"] = (span_hrs - df["hours_logged"].astype(float)).clip(lower=0).round(2)

    df["first_clock_in"] = first_ts.map(_to_ist_str)
    df["last_clock_out"]  = last_ts.map(_to_ist_str)
    df["leave_type"]      = df["leave_type"].fillna("")

    df = df.rename(columns={
        "hours_logged":   "Total Hours",
        "session_count":  "Sessions",
        "first_clock_in": "Clock In",
        "last_clock_out": "Clock Out",
        "leave_type":     "Leave",
    })
    df = df.sort_values(["Total Hours", "Employee"]).drop(columns=["snapshot_date", "pulled_at"])
    # Leave moved to col 3 so it's always visible; _daily_target retained for
    # per-employee alert thresholds and dropped before display.
    return df[["Employee", "Type", "Leave", "Total Hours", "Break Hrs", "Sessions", "Clock In", "Clock Out", "_daily_target"]].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_weekly_summary(week_start: str, week_end: str) -> pd.DataFrame:
    """
    Compute weekly summary LIVE from daily_snapshots — never reads the cached
    weekly_summaries table, so retroactive leave approvals are reflected the
    moment the engine re-syncs those days regardless of how old the week is.
    Targets are pro-rated by each employee's active range so joiners /
    departures within the week are handled correctly.
    """
    data = _fetch_all(lambda: (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, leave_type, "
                "employees(jibble_name, display_name, employment_type, weekly_target_hrs, daily_target_hrs, joined_date, departed_date)")
        .gte("snapshot_date", week_start)
        .lte("snapshot_date", week_end)
        .order("id")
    ))
    df = pd.DataFrame(data)
    if df.empty:
        return df

    emp_cols = pd.json_normalize(df["employees"])
    df = df.drop(columns=["employees"])
    df["Employee"]       = _display_names(emp_cols)
    df["weekly_target"]  = emp_cols["weekly_target_hrs"].astype(float)
    df["daily_target"]   = emp_cols["daily_target_hrs"].astype(float)
    df["_joined"]        = emp_cols["joined_date"].map(_parse_date)
    df["_departed"]      = emp_cols["departed_date"].map(_parse_date)
    df["leave_type"]     = df["leave_type"].fillna("")
    df["hours_logged"]   = df["hours_logged"].astype(float)
    # Excused = personal leave OR public holiday (both reduce the target).
    # Leave  = personal leave only (holidays are not tallied as leave).
    df["_excused"]       = df["leave_type"] != ""
    df["_leave"]         = df["_excused"] & ~df["leave_type"].isin(HOLIDAY_LEAVE_TYPES)
    # Weekend catch-up hours count toward the week's total but never raise the
    # target — surfaced separately so it's clear where the hours came from.
    df["_weekend_hrs"]   = df["hours_logged"].where(
        pd.to_datetime(df["snapshot_date"]).dt.weekday >= 5, 0.0)

    # Drop snapshot rows outside each employee's active range
    df = _filter_active_on(df)
    if df.empty:
        return df

    monday = date.fromisoformat(week_start)
    friday = date.fromisoformat(week_end)

    agg = (
        df.groupby("Employee")
        .agg(
            Hours        = ("hours_logged", "sum"),
            Weekend_Hrs  = ("_weekend_hrs", "sum"),
            Excused_Days = ("_excused", "sum"),
            Leave_Days   = ("_leave",   "sum"),
            weekly_target= ("weekly_target", "first"),
            daily_target = ("daily_target",  "first"),
            _joined      = ("_joined",       "first"),
            _departed    = ("_departed",     "first"),
        )
        .reset_index()
    )

    # Pro-rated target: working days within active range × daily_target,
    # minus leave days within that window.
    agg["active_days"] = agg.apply(
        lambda r: _working_days_active(monday, friday, r["_joined"], r["_departed"]),
        axis=1,
    )
    agg = agg[agg["active_days"] > 0]   # drop employees with no overlap
    agg["Target"]  = ((agg["active_days"] - agg["Excused_Days"]) * agg["daily_target"]).clip(lower=0).round(2)
    agg["Deficit"] = (agg["Target"] - agg["Hours"]).clip(lower=0).round(2)

    def _status(row):
        if row["Hours"] >= row["Target"]:     return "Met"
        if row["Hours"] >= row["Target"] - 4: return "At Risk"
        return "Deficit"

    agg["Status"] = agg.apply(_status, axis=1)
    order = {"Deficit": 0, "At Risk": 1, "Met": 2}
    agg = agg.sort_values("Status", key=lambda s: s.map(order))
    agg = agg.rename(columns={"Leave_Days": "Leave Days", "Weekend_Hrs": "Weekend Hrs"})
    cols = ["Employee", "Status", "Hours", "Target", "Deficit", "Leave Days"]
    if agg["Weekend Hrs"].sum() > 0:   # only shown in weeks someone worked one
        cols.insert(4, "Weekend Hrs")
    return agg[cols].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_current_week(monday: str, through: str) -> pd.DataFrame:
    if monday > through:
        return pd.DataFrame()

    data = _fetch_all(lambda: (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, leave_type, "
                "employees(jibble_name, display_name, employment_type, weekly_target_hrs, daily_target_hrs, joined_date, departed_date)")
        .gte("snapshot_date", monday)
        .lte("snapshot_date", through)
        .order("id")
    ))
    df = pd.DataFrame(data)
    if df.empty:
        return df

    emp_cols = pd.json_normalize(df["employees"])
    df = df.drop(columns=["employees"])
    df["Employee"]      = _display_names(emp_cols)
    df["weekly_target"] = emp_cols["weekly_target_hrs"].astype(float)
    df["daily_target"]  = emp_cols["daily_target_hrs"].astype(float)
    df["_joined"]       = emp_cols["joined_date"].map(_parse_date)
    df["_departed"]     = emp_cols["departed_date"].map(_parse_date)
    df["leave_type"]    = df["leave_type"].fillna("")
    df["_excused"]      = df["leave_type"] != ""
    df["_leave"]        = df["_excused"] & ~df["leave_type"].isin(HOLIDAY_LEAVE_TYPES)

    df = _filter_active_on(df)
    if df.empty:
        return df

    monday_date = date.fromisoformat(monday)
    friday_date = monday_date + timedelta(days=4)
    today       = _today()

    # Split hours into completed days vs today: today's numbers are partial
    # (the engine syncs intra-day), so the projection must not treat today as a
    # finished day — that used to show most of the team in false "Deficit"
    # every morning.
    df["hours_logged"] = df["hours_logged"].astype(float)
    snap_dates         = pd.to_datetime(df["snapshot_date"]).dt.date
    # Only a *scheduled* day in progress is held back from the banked total and
    # extrapolated instead; weekend catch-up hours are voluntary and always
    # count in full, including on the day they're worked.
    _hold_back         = (snap_dates == today) & (today.weekday() < 5)
    df["_hours_pre"]   = df["hours_logged"].where(~_hold_back, 0.0)
    df["_leave_today"] = df["_excused"] & (snap_dates == today)
    df["_weekend_hrs"] = df["hours_logged"].where(
        pd.to_datetime(df["snapshot_date"]).dt.weekday >= 5, 0.0)

    agg = (
        df.groupby("Employee")
        .agg(
            Hours        = ("hours_logged", "sum"),
            Hours_Pre    = ("_hours_pre",   "sum"),
            Weekend_Hrs  = ("_weekend_hrs", "sum"),
            Excused_Days = ("_excused", "sum"),
            Leave_Days   = ("_leave",   "sum"),
            Leave_Today  = ("_leave_today", "max"),
            weekly_target= ("weekly_target", "first"),
            daily_target = ("daily_target",  "first"),
            _joined      = ("_joined",       "first"),
            _departed    = ("_departed",     "first"),
        )
        .reset_index()
    )

    # Pro-rated target uses active working days within Mon-Fri
    agg["active_days"] = agg.apply(
        lambda r: _working_days_active(monday_date, friday_date, r["_joined"], r["_departed"]),
        axis=1,
    )
    agg = agg[agg["active_days"] > 0]
    agg["Target"] = ((agg["active_days"] - agg["Excused_Days"]) * agg["daily_target"]).clip(lower=0)

    # Projected end-of-week = hours banked before today + (today and the
    # remaining working days at target pace, skipping a known leave day today).
    def _remaining_days(r):
        days = 0
        d = today
        while d <= friday_date:
            if d.weekday() < 5 \
               and (r["_joined"] is None or d >= r["_joined"]) \
               and (r["_departed"] is None or d <= r["_departed"]):
                days += 1
            d += timedelta(days=1)
        if r["Leave_Today"] and days > 0:
            days -= 1
        return days

    agg["Days Left"] = agg.apply(_remaining_days, axis=1)
    agg["Projected"] = (agg["Hours_Pre"] + agg["Days Left"] * agg["daily_target"]).round(2)

    def _status(row):
        if row["Projected"] >= row["Target"]:     return "On Track"
        if row["Projected"] >= row["Target"] - 4: return "At Risk"
        return "Deficit"

    agg["Status"] = agg.apply(_status, axis=1)
    order = {"Deficit": 0, "At Risk": 1, "On Track": 2}
    agg = agg.sort_values("Status", key=lambda s: s.map(order))
    agg = agg.rename(columns={"Leave_Days": "Leave Days", "Weekend_Hrs": "Weekend Hrs"})
    # Status first
    cols = ["Employee", "Status", "Hours", "Target", "Projected", "Leave Days", "Days Left"]
    if agg["Weekend Hrs"].sum() > 0:
        cols.insert(5, "Weekend Hrs")
    return agg[cols].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_monthly_summary(start: str, end: str) -> pd.DataFrame:
    data = _fetch_all(lambda: (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, leave_type, "
                "employees(jibble_name, display_name, employment_type, weekly_target_hrs, daily_target_hrs, joined_date, departed_date)")
        .gte("snapshot_date", start)
        .lte("snapshot_date", end)
        .order("id")
    ))
    df = pd.DataFrame(data)
    if df.empty:
        return df

    emp_cols = pd.json_normalize(df["employees"])
    df = df.drop(columns=["employees"])
    df["Employee"]     = _display_names(emp_cols)
    df["daily_target"] = emp_cols["daily_target_hrs"].astype(float)
    df["_joined"]      = emp_cols["joined_date"].map(_parse_date)
    df["_departed"]    = emp_cols["departed_date"].map(_parse_date)
    df["leave_type"]   = df["leave_type"].fillna("")
    df["hours_logged"] = df["hours_logged"].astype(float)
    # Excused = personal leave OR public holiday (both reduce expected hours).
    # Leave  = personal leave only (holidays are not tallied as leave).
    df["_excused"]     = df["leave_type"] != ""
    df["_leave"]       = df["_excused"] & ~df["leave_type"].isin(HOLIDAY_LEAVE_TYPES)
    df["_weekend_hrs"] = df["hours_logged"].where(
        pd.to_datetime(df["snapshot_date"]).dt.weekday >= 5, 0.0)

    # Drop snapshot rows outside each employee's active range
    df = _filter_active_on(df)
    if df.empty:
        return df

    # Compute Expected Hrs per-employee as (working_days in active range ∩ [start,end] − leave_days) × daily_target.
    start_d = date.fromisoformat(start)
    end_d   = date.fromisoformat(end)

    def _working_days_in_range(joined, departed) -> int:
        """Count Mon-Fri days in [start_d, end_d] within employee's active range."""
        lo = max(start_d, joined)   if joined   else start_d
        hi = min(end_d,   departed) if departed else end_d
        if hi < lo:
            return 0
        return sum(
            1 for i in range((hi - lo).days + 1)
            if (lo + timedelta(days=i)).weekday() < 5
        )

    agg = (
        df.groupby("Employee")
        .agg(
            Total_Hours  = ("hours_logged", "sum"),
            Weekend_Hrs  = ("_weekend_hrs", "sum"),
            Days_Present = ("hours_logged", lambda x: (x > 0).sum()),
            Days_Absent  = ("hours_logged", lambda x: ((x == 0) & (df.loc[x.index, "leave_type"] == "")).sum()),
            Excused_Days = ("_excused", "sum"),
            Leave_Days   = ("_leave",   "sum"),
            daily_target = ("daily_target", "first"),
            _joined      = ("_joined",       "first"),
            _departed    = ("_departed",     "first"),
        )
        .reset_index()
    )
    agg["working_days"] = agg.apply(
        lambda r: _working_days_in_range(r["_joined"], r["_departed"]), axis=1
    )
    agg = agg[agg["working_days"] > 0]
    agg["Expected Hrs"] = ((agg["working_days"] - agg["Excused_Days"]) * agg["daily_target"]).clip(lower=0).round(2)
    # Net (±) instead of deficit-only: surplus hours are informative too, and a
    # one-sided "Deficit" column hides people consistently over target.
    agg["Net Hrs"] = (agg["Total_Hours"] - agg["Expected Hrs"]).round(2)
    agg = agg.sort_values("Net Hrs")
    agg = agg.rename(columns={
        "Total_Hours": "Hours", "Days_Present": "Days Present",
        "Days_Absent": "Days Absent", "Leave_Days": "Leave Days",
        "Weekend_Hrs": "Weekend Hrs",
    })
    cols = ["Employee", "Net Hrs", "Hours", "Expected Hrs", "Days Present", "Days Absent", "Leave Days"]
    if agg["Weekend Hrs"].sum() > 0:
        cols.insert(4, "Weekend Hrs")
    return agg[cols].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_anomalies(start: str, end: str) -> pd.DataFrame:
    data = _fetch_all(lambda: (
        sb.table("anomalies")
        .select("anomaly_date, anomaly_type, detail, employees(jibble_name, display_name, joined_date, departed_date)")
        .gte("anomaly_date", start)
        .lte("anomaly_date", end)
        .order("id")
    ))
    df = pd.DataFrame(data)
    if df.empty:
        return df

    emp = pd.json_normalize(df["employees"])
    df  = df.drop(columns=["employees"])
    df["Employee"]  = _display_names(emp)
    df["_joined"]   = emp["joined_date"].map(_parse_date)
    df["_departed"] = emp["departed_date"].map(_parse_date)
    df = df.rename(columns={"anomaly_date": "Date", "anomaly_type": "Type", "detail": "Detail"})

    # Hide deprecated anomaly types (Excessive Breaks, Early Departure) — they
    # are no longer generated but historical rows still exist.
    df = df[~df["Type"].isin(HIDDEN_ANOMALY_TYPES)]
    # Hide anomalies outside the employee's active range (e.g. stale Absence
    # flags for someone who'd already left or hadn't joined yet)
    df = _filter_active_on(df, snap_date_col="Date")
    df = df.drop(columns=["_joined", "_departed"])
    if df.empty:
        return df
    df["_sev"] = df["Type"].map(ANOMALY_SEVERITY).fillna(99)
    df = df.sort_values(["_sev", "Date"], ascending=[True, False]).drop(columns=["_sev"])
    return df[["Date", "Employee", "Type", "Detail"]].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_anomaly_summary(start: str, end: str) -> pd.DataFrame:
    df = load_anomalies(start, end)
    if df.empty:
        return df

    type_cols = sorted(ANOMALY_SEVERITY, key=ANOMALY_SEVERITY.get)
    records = []
    for emp, grp in df.groupby("Employee"):
        row = {"Employee": emp, "Total": len(grp)}
        for t in type_cols:
            row[t] = int((grp["Type"] == t).sum())
        records.append(row)
    return pd.DataFrame(records).sort_values("Total", ascending=False).reset_index(drop=True)


@st.cache_data(ttl=300)
def load_employees() -> pd.DataFrame:
    """Full roster with targets and active ranges (for drill-down and
    'expected but missing' checks)."""
    res = sb.table("employees").select(
        "member_id, jibble_name, display_name, employment_type, "
        "weekly_target_hrs, daily_target_hrs, is_active, is_excluded, "
        "joined_date, departed_date"
    ).execute()
    df = pd.DataFrame(res.data)
    if df.empty:
        return df
    df["display_name"] = df["display_name"].fillna(df["jibble_name"])
    df["_joined"]      = df["joined_date"].map(_parse_date)
    df["_departed"]    = df["departed_date"].map(_parse_date)
    return df


@st.cache_data(ttl=60)
def load_member_daily(member_id: str, start: str, end: str) -> pd.DataFrame:
    """Per-day rows for one employee, formatted like the day view."""
    data = _fetch_all(lambda: (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, session_count, first_clock_in, last_clock_out, leave_type")
        .eq("member_id", member_id)
        .gte("snapshot_date", start)
        .lte("snapshot_date", end)
        .order("snapshot_date", desc=True)
    ))
    df = pd.DataFrame(data)
    if df.empty:
        return df
    df["hours_logged"] = df["hours_logged"].astype(float)
    df["leave_type"]   = df["leave_type"].fillna("")
    first_ts = df["first_clock_in"].map(_parse_utc)
    last_ts  = df["last_clock_out"].map(_parse_utc)
    span = pd.Series(
        [(lo - fi).total_seconds() / 3600 if pd.notna(fi) and pd.notna(lo) else float("nan")
         for fi, lo in zip(first_ts, last_ts)],
        index=df.index,
    )
    df["Break Hrs"] = (span - df["hours_logged"]).clip(lower=0).round(2)
    df["Clock In"]  = first_ts.map(_to_ist_str)
    df["Clock Out"] = last_ts.map(_to_ist_str)
    df = df.rename(columns={
        "snapshot_date": "Date", "hours_logged": "Hours",
        "session_count": "Sessions", "leave_type": "Leave",
    })
    return df[["Date", "Hours", "Break Hrs", "Sessions", "Clock In", "Clock Out", "Leave"]].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_leave_rows(start: str, end: str) -> pd.DataFrame:
    """All leave/holiday snapshot rows in range (for the Leaves summary)."""
    data = _fetch_all(lambda: (
        sb.table("daily_snapshots")
        .select("snapshot_date, leave_type, employees(jibble_name, display_name, joined_date, departed_date)")
        .gte("snapshot_date", start)
        .lte("snapshot_date", end)
        .not_.is_("leave_type", "null")
        .order("id")
    ))
    df = pd.DataFrame(data)
    if df.empty:
        return df
    emp = pd.json_normalize(df["employees"])
    df  = df.drop(columns=["employees"])
    df["Employee"]  = _display_names(emp)
    df["_joined"]   = emp["joined_date"].map(_parse_date)
    df["_departed"] = emp["departed_date"].map(_parse_date)
    df = _filter_active_on(df)
    return df[["snapshot_date", "leave_type", "Employee"]].reset_index(drop=True)


# ---------------------------------------------------------------------------
# Stylers
# ---------------------------------------------------------------------------

def _color_status(val):
    return {
        "Met":      "color:#4ade80; font-weight:700",
        "On Track": "color:#4ade80; font-weight:700",
        "At Risk":  "color:#fbbf24; font-weight:700",
        "Deficit":  "color:#f87171; font-weight:700",
    }.get(val, "")

def _color_anomaly(val):
    if val in _CRITICAL: return "color:#f87171; font-weight:700"
    if val in _WARNING:  return "color:#fbbf24; font-weight:600"
    return "color:#60a5fa; font-weight:600"

def _color_hours(val):
    try:
        h = float(val)
    except (TypeError, ValueError):
        return ""
    if h == 0:  return "color:#f87171; font-weight:700"
    if h < 4:   return "color:#fbbf24; font-weight:600"
    if h >= 10: return "color:#60a5fa; font-weight:600"
    return ""  # normal range — use theme default so it's readable on both light and dark

def _color_weekend(val):
    try:
        h = float(val)
    except (TypeError, ValueError):
        return ""
    return "color:#60a5fa; font-weight:600" if h > 0 else "color:#475569"

def _color_net(val):
    try:
        h = float(val)
    except (TypeError, ValueError):
        return ""
    if h >= 0:  return "color:#4ade80; font-weight:600"
    if h >= -4: return "color:#fbbf24; font-weight:600"
    return "color:#f87171; font-weight:700"

def _color_deficit(val):
    try:
        h = float(val)
    except (TypeError, ValueError):
        return ""
    if h > 4: return "color:#f87171; font-weight:700"
    if h > 0: return "color:#fbbf24; font-weight:600"
    return "color:#4ade80; font-weight:600"

def _color_absent(val):
    try:
        v = int(val)
    except (TypeError, ValueError):
        return ""
    if v == 0: return "color:#4ade80"
    if v <= 2: return "color:#fbbf24; font-weight:600"
    return "color:#f87171; font-weight:700"

def _heat_count(val):
    try:
        v = int(val)
    except (TypeError, ValueError):
        return ""
    if v == 0: return "color:#475569"
    if v == 1: return "color:#fbbf24; font-weight:600"
    return "color:#f87171; font-weight:700"


# ---------------------------------------------------------------------------
# Page header
# ---------------------------------------------------------------------------

_hdr_col, _sync_col, _ref_col = st.columns([5, 2, 1])
_hdr_col.markdown("## 📋 Attendance Dashboard")

_sync_ts  = _parse_utc(load_last_synced())
_sync_ist = _sync_ts.tz_convert("Asia/Kolkata") if pd.notna(_sync_ts) else None
if _sync_ist is not None:
    _sync_label = _sync_ist.strftime("%I:%M %p").lstrip("0") + _sync_ist.strftime(", %a %d %b")
    # Stale = last sync is older than the previous working day (weekends OK:
    # Monday morning showing Friday-night data is normal, Tuesday isn't).
    _prev_wd = _today() - timedelta(days=1)
    while _prev_wd.weekday() >= 5:
        _prev_wd -= timedelta(days=1)
    if _sync_ist.date() < _prev_wd:
        _sync_col.markdown(
            f'<div style="text-align:right;padding-top:14px;font-size:0.78rem;color:#fbbf24;">'
            f'⚠️ Last synced <b>{_sync_label} IST</b> — data may be behind</div>',
            unsafe_allow_html=True,
        )
    else:
        _sync_col.markdown(
            f'<div style="text-align:right;padding-top:14px;font-size:0.78rem;opacity:0.65;">'
            f'⏱ Engine last synced: <b>{_sync_label} IST</b></div>',
            unsafe_allow_html=True,
        )
if _ref_col.button("🔄", key="global_refresh", help="Refresh all data"):
    load_daily_snapshot.clear()
    load_last_synced.clear()
    load_weekly_summary.clear()
    load_current_week.clear()
    load_monthly_summary.clear()
    load_anomalies.clear()
    load_anomaly_summary.clear()
    load_employees.clear()
    load_member_daily.clear()
    load_leave_rows.clear()
    st.rerun()
st.markdown("---")

# ---------------------------------------------------------------------------
# Tabs
# ---------------------------------------------------------------------------

tab1, tab2, tab3, tab4, tab5 = st.tabs(
    ["Attendance", "Anomalies", "Anomaly Breakdown", "Employee", "Leaves"]
)


# ── Tab 1: Attendance ─────────────────────────────────────────────────────────

with tab1:
    today = _today()
    start_str, end_str, gran = range_picker("att")
    start = date.fromisoformat(start_str)
    end   = date.fromisoformat(end_str)

    st.markdown("---")

    # ── Day view ─────────────────────────────────────────────────────────────
    if gran == "day":
        df = load_daily_snapshot(start_str)
        is_wknd = start.weekday() >= 5
        if df.empty:
            if is_wknd:
                st.info(
                    f"Nobody logged hours on {start.strftime('%A, %d %b %Y')}. "
                    "Weekends only appear here when someone actually worked."
                )
            elif start == today:
                st.info(
                    f"No snapshot data yet for {start.strftime('%A, %d %b %Y')}. "
                    "The engine's first sync of a new day runs at ~1 PM IST "
                    "(the morning run re-syncs yesterday and earlier)."
                )
            else:
                st.info(f"No snapshot data for {start.strftime('%A, %d %b %Y')}. The engine may not have run for this date.")
        else:
            if start == today and _sync_ist is not None and _sync_ist.date() == today:
                st.caption(
                    f"⏱ In-progress day — totals are partial (as of {_sync_label} IST) "
                    "and update every engine sync."
                )

            if is_wknd:
                st.markdown(
                    f'<div class="alert alert-blue">🗓️ <b>Weekend — {len(df)} '
                    f'{"person" if len(df) == 1 else "people"} worked.</b> These hours '
                    'count toward the week; no one is expected in, so absence and '
                    'late checks do not apply.</div>',
                    unsafe_allow_html=True,
                )

            # On a weekend only people who worked have rows, so "absent" and
            # "below half-day" would fire against the whole team / against
            # anyone doing a short catch-up stint. Suppress both.
            _none    = df.iloc[0:0]
            absent   = _none if is_wknd else df[(df["Total Hours"] == 0) & (df["Leave"] == "")]
            # Threshold is per-employee (half their daily target) so part-timers
            # aren't flagged against a full-timer's bar.
            low_hrs  = _none if is_wknd else df[(df["Total Hours"] > 0) & (df["Leave"] == "")
                          & (df["Total Hours"] < df["_daily_target"] * 0.5)]
            holiday  = df[df["Leave"].isin(HOLIDAY_LEAVE_TYPES)]
            on_leave = df[(df["Leave"] != "") & (~df["Leave"].isin(HOLIDAY_LEAVE_TYPES))]

            if not absent.empty:
                names = ", ".join(absent["Employee"].tolist())
                st.markdown(f'<div class="alert alert-red">🔴 <b>Absent, no leave ({len(absent)}):</b> {names}</div>', unsafe_allow_html=True)
            if not low_hrs.empty:
                names = ", ".join(low_hrs["Employee"].tolist())
                st.markdown(f'<div class="alert alert-yellow">⚠️ <b>Below half-day hours ({len(low_hrs)}):</b> {names}</div>', unsafe_allow_html=True)
            if not on_leave.empty:
                names = ", ".join(on_leave["Employee"].tolist())
                st.markdown(f'<div class="alert alert-blue">🔵 <b>On leave ({len(on_leave)}):</b> {names}</div>', unsafe_allow_html=True)
            if not holiday.empty:
                hname = holiday["Leave"].mode().iloc[0]
                st.markdown(f'<div class="alert alert-blue">🎉 <b>{hname}:</b> {len(holiday)} staff off (company holiday, not counted as leave)</div>', unsafe_allow_html=True)

            # Active employees with no snapshot row at all — a silent sync gap
            # is easy to miss when someone simply doesn't appear in the table.
            roster = load_employees()
            if not roster.empty and not is_wknd:
                active_today = {
                    r["display_name"]
                    for _, r in roster.iterrows()
                    if not r["is_excluded"] and r.get("is_active", True)
                    and (r["_joined"] is None or start >= r["_joined"])
                    and (r["_departed"] is None or start <= r["_departed"])
                }
                missing = sorted(active_today - set(df["Employee"]))
                if missing:
                    st.markdown(f'<div class="alert alert-blue">❔ <b>No data ({len(missing)}):</b> {", ".join(missing)}</div>', unsafe_allow_html=True)

            if absent.empty and low_hrs.empty and not is_wknd:
                st.markdown('<div class="alert alert-green">✅ No attendance issues.</div>', unsafe_allow_html=True)

            c1, c2, c3, c4, c5 = st.columns(5)
            c1.metric("Present",    int((df["Total Hours"] > 0).sum()))
            c2.metric("Absent",     len(absent))
            c3.metric("On Leave",   len(on_leave))
            present_hrs = df[df["Total Hours"] > 0]["Total Hours"]
            c4.metric("Avg Hours",  _fmt_hrs(present_hrs.mean() if not present_hrs.empty else 0))
            c5.metric("Avg Breaks", _fmt_hrs(df["Break Hrs"].mean()))

            st.markdown("&nbsp;", unsafe_allow_html=True)
            display_df = df.drop(columns=["_daily_target"])
            styled = (
                display_df.style
                .map(_color_hours, subset=["Total Hours"])
                .map(_color_deficit, subset=["Break Hrs"])
                .format({"Total Hours": _fmt_hrs, "Break Hrs": _fmt_hrs})
            )
            st.dataframe(styled, use_container_width=True, hide_index=True)
            _csv_button(display_df, f"attendance_{start_str}.csv", key="att_day_csv")

    # ── Week view ─────────────────────────────────────────────────────────────
    elif gran == "week":
        this_monday      = today - timedelta(days=today.weekday())
        is_current_week  = (start == this_monday)

        if is_current_week:
            through = min(end, today).isoformat()
            df = load_current_week(start_str, through)
            if df.empty:
                st.info("No data yet for this week.")
            else:
                st.markdown(f"**Week of {start.strftime('%d %b %Y')}** · Live")
                st.caption(
                    "Projected = hours completed before today + remaining working days "
                    "(incl. today) at target pace. Today's partial hours count toward "
                    "Hours but are not extrapolated."
                )

                deficit_emp = df[df["Status"] == "Deficit"]
                at_risk_emp = df[df["Status"] == "At Risk"]
                if not deficit_emp.empty:
                    names = ", ".join(deficit_emp["Employee"].tolist())
                    st.markdown(f'<div class="alert alert-red">🔴 <b>Projected deficit ({len(deficit_emp)}):</b> {names}</div>', unsafe_allow_html=True)
                if not at_risk_emp.empty:
                    names = ", ".join(at_risk_emp["Employee"].tolist())
                    st.markdown(f'<div class="alert alert-yellow">⚠️ <b>At risk ({len(at_risk_emp)}):</b> {names}</div>', unsafe_allow_html=True)
                if deficit_emp.empty and at_risk_emp.empty:
                    st.markdown('<div class="alert alert-green">✅ Everyone is on track this week.</div>', unsafe_allow_html=True)

                c1, c2, c3 = st.columns(3)
                c1.metric("On Track", int((df["Status"] == "On Track").sum()))
                c2.metric("At Risk",  int((df["Status"] == "At Risk").sum()))
                c3.metric("Deficit",  int((df["Status"] == "Deficit").sum()))

                st.markdown("&nbsp;", unsafe_allow_html=True)
                styled = _style_weekend(
                    df.style
                    .map(_color_status, subset=["Status"])
                    .format(_fmt_map(df, {"Hours": _fmt_hrs, "Target": _fmt_hrs,
                                          "Projected": _fmt_hrs, "Weekend Hrs": _fmt_hrs})),
                    df,
                )
                st.dataframe(styled, use_container_width=True, hide_index=True)
                _csv_button(df, f"week_{start_str}.csv", key="att_curweek_csv")

        else:
            df = load_weekly_summary(start_str, end_str)
            if df.empty:
                st.info(
                    f"No snapshot data for the week of {start.strftime('%d %b %Y')}. "
                    "This week may not have been processed yet — try running: "
                    "`python main.py --date " + end_str + "`"
                )
            else:
                deficit_emp = df[df["Status"] == "Deficit"]
                at_risk_emp = df[df["Status"] == "At Risk"]
                if not deficit_emp.empty:
                    names = ", ".join(deficit_emp["Employee"].tolist())
                    st.markdown(f'<div class="alert alert-red">🔴 <b>Deficit ({len(deficit_emp)}):</b> {names}</div>', unsafe_allow_html=True)
                if not at_risk_emp.empty:
                    names = ", ".join(at_risk_emp["Employee"].tolist())
                    st.markdown(f'<div class="alert alert-yellow">⚠️ <b>At risk ({len(at_risk_emp)}):</b> {names}</div>', unsafe_allow_html=True)
                if deficit_emp.empty and at_risk_emp.empty:
                    st.markdown('<div class="alert alert-green">✅ All targets met this week.</div>', unsafe_allow_html=True)

                c1, c2, c3 = st.columns(3)
                c1.metric("Met",     int((df["Status"] == "Met").sum()))
                c2.metric("At Risk", int((df["Status"] == "At Risk").sum()))
                c3.metric("Deficit", int((df["Status"] == "Deficit").sum()))

                st.markdown("&nbsp;", unsafe_allow_html=True)
                styled = _style_weekend(
                    df.style
                    .map(_color_status,  subset=["Status"])
                    .map(_color_deficit, subset=["Deficit"])
                    .format(_fmt_map(df, {"Hours": _fmt_hrs, "Target": _fmt_hrs,
                                          "Deficit": _fmt_hrs, "Weekend Hrs": _fmt_hrs})),
                    df,
                )
                st.dataframe(styled, use_container_width=True, hide_index=True)
                _csv_button(df, f"week_{start_str}.csv", key="att_pastweek_csv")

    # ── Month / range view ────────────────────────────────────────────────────
    else:
        df = load_monthly_summary(start_str, end_str)
        if df.empty:
            st.info(f"No data for this period.")
        else:
            last_day_of_month = calendar.monthrange(end.year, end.month)[1]
            is_partial = (start.day == 1 and end < date(end.year, end.month, last_day_of_month))
            label      = _range_label(start, end, "month")
            partial_note = (
                f" · ⚠️ Partial — {end.day} of {last_day_of_month} days elapsed"
                if is_partial else ""
            )
            st.markdown(f"**{label}**{partial_note}")

            # Enrich with anomaly counts so the month view doubles as a
            # per-employee reliability roll-up.
            summ = load_anomaly_summary(start_str, end_str)
            if not summ.empty:
                s_idx = summ.set_index("Employee")
                df["Lates"]     = df["Employee"].map(s_idx["Late / No Start"].to_dict()).fillna(0).astype(int)
                df["Anomalies"] = df["Employee"].map(s_idx["Total"].to_dict()).fillna(0).astype(int)
            else:
                df["Lates"]     = 0
                df["Anomalies"] = 0

            high_def = df[df["Net Hrs"] < -8]
            if not high_def.empty:
                names = ", ".join(high_def["Employee"].tolist())
                st.markdown(f'<div class="alert alert-red">🔴 <b>More than 8h behind ({len(high_def)}):</b> {names}</div>', unsafe_allow_html=True)

            c1, c2, c3 = st.columns(3)
            c1.metric("Total Hours",          _fmt_hrs(df["Hours"].sum()))
            c2.metric("Avg per Employee",     _fmt_hrs(df["Hours"].mean()))
            c3.metric("Team Net vs Expected", _fmt_hrs_signed(df["Net Hrs"].sum()))

            st.markdown("&nbsp;", unsafe_allow_html=True)
            styled = _style_weekend(
                df.style
                .map(_color_net,    subset=["Net Hrs"])
                .map(_color_absent, subset=["Days Absent"])
                .map(_heat_count,   subset=["Lates", "Anomalies"])
                .format(_fmt_map(df, {"Hours": _fmt_hrs, "Expected Hrs": _fmt_hrs,
                                      "Net Hrs": _fmt_hrs_signed, "Weekend Hrs": _fmt_hrs})),
                df,
            )
            st.dataframe(styled, use_container_width=True, hide_index=True)
            _csv_button(df, f"range_{start_str}_to_{end_str}.csv", key="att_month_csv")


# ── Tab 2: Anomalies ──────────────────────────────────────────────────────────

with tab2:
    start_str, end_str, _ = range_picker("ano")

    df = load_anomalies(start_str, end_str)

    st.markdown("---")

    if df.empty:
        st.info("No anomalies in the selected date range.")
    else:
        col_a, col_b = st.columns(2)
        with col_a:
            types    = ["All"] + sorted(df["Type"].unique().tolist())
            sel_type = st.selectbox("Anomaly type", types)
        with col_b:
            emps    = ["All"] + sorted(df["Employee"].unique().tolist())
            sel_emp = st.selectbox("Employee", emps)

        if sel_type != "All": df = df[df["Type"] == sel_type]
        if sel_emp  != "All": df = df[df["Employee"] == sel_emp]

        n_critical = int(df["Type"].isin(_CRITICAL).sum())
        n_warning  = int(df["Type"].isin(_WARNING).sum())
        n_info     = len(df) - n_critical - n_warning

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Total",    len(df))
        c2.metric("Critical", n_critical)
        c3.metric("Warning",  n_warning)
        c4.metric("Info",     n_info)

        st.markdown("&nbsp;", unsafe_allow_html=True)
        st.caption("Sorted by severity · Critical (red) → Warning (amber) → Info (blue)")
        styled = df.style.map(_color_anomaly, subset=["Type"])
        st.dataframe(styled, use_container_width=True, hide_index=True)
        _csv_button(df, f"anomalies_{start_str}_to_{end_str}.csv", key="ano_csv")


# ── Tab 3: Anomaly Breakdown ──────────────────────────────────────────────────

with tab3:
    start_str, end_str, _ = range_picker("brk")

    df = load_anomaly_summary(start_str, end_str)

    st.markdown("---")

    if df.empty:
        st.info("No anomaly data in the selected date range.")
    else:
        st.markdown("**Breakdown by employee** · sorted by total anomalies")
        st.markdown(
            '<div style="font-size:0.82rem;opacity:0.7;margin-bottom:12px;">'
            '🔵 0 = none &nbsp;·&nbsp; 🟡 1 = amber &nbsp;·&nbsp; 🔴 2+ = red'
            '</div>',
            unsafe_allow_html=True,
        )
        num_cols = [c for c in df.columns if c != "Employee"]
        styled = df.style.map(_heat_count, subset=num_cols)
        st.dataframe(styled, use_container_width=True, hide_index=True)


# ── Tab 4: Employee drill-down ────────────────────────────────────────────────

with tab4:
    roster_all = load_employees()
    if roster_all.empty:
        st.info("No employees synced yet.")
    else:
        roster = roster_all[~roster_all["is_excluded"]].copy()
        _t = _today()
        roster["_label"] = [
            r["display_name"] + (" (departed)" if r["_departed"] is not None and r["_departed"] < _t else "")
            for _, r in roster.iterrows()
        ]
        roster = roster.sort_values("_label")

        sel_col, _ = st.columns([2, 5])
        sel_label = sel_col.selectbox("Employee", roster["_label"].tolist(), key="emp_sel")
        emp_row   = roster[roster["_label"] == sel_label].iloc[0]

        start_str, end_str, _gran = range_picker("emp")
        st.markdown("---")

        ddf = load_member_daily(emp_row["member_id"], start_str, end_str)
        if ddf.empty:
            st.info("No attendance data for this employee in the selected range.")
        else:
            # Metrics use completed days only — today's numbers are partial and
            # would overstate Expected / understate Net while the day is live.
            _t2   = _today()
            dates = pd.to_datetime(ddf["Date"]).dt.date
            comp  = ddf[dates < _t2]
            live_partial = bool((dates == _t2).any())
            base  = comp if not comp.empty else ddf

            excused  = int((base["Leave"] != "").sum())
            personal = int(((base["Leave"] != "") & (~base["Leave"].isin(HOLIDAY_LEAVE_TYPES))).sum())

            s_d, e_d = date.fromisoformat(start_str), date.fromisoformat(end_str)
            lo = max(s_d, emp_row["_joined"])   if emp_row["_joined"]   else s_d
            hi = min(e_d, emp_row["_departed"]) if emp_row["_departed"] else e_d
            if not comp.empty:
                hi = min(hi, _t2 - timedelta(days=1))
            wdays = (
                sum(1 for i in range((hi - lo).days + 1) if (lo + timedelta(days=i)).weekday() < 5)
                if hi >= lo else 0
            )
            expected = max(0.0, (wdays - excused) * float(emp_row["daily_target_hrs"]))
            hours    = float(base["Hours"].sum())

            if live_partial and not comp.empty:
                st.caption("⏱ Today is in progress — the metrics below cover completed days only; today's partial hours appear in the daily log.")

            ano_all = load_anomalies(start_str, end_str)
            my_ano  = ano_all[ano_all["Employee"] == emp_row["display_name"]] if not ano_all.empty else ano_all
            lates   = int((my_ano["Type"] == "Late / No Start").sum()) if not my_ano.empty else 0

            c1, c2, c3, c4, c5, c6 = st.columns(6)
            c1.metric("Hours",     _fmt_hrs(hours))
            c2.metric("Expected",  _fmt_hrs(expected))
            c3.metric("Net",       _fmt_hrs_signed(hours - expected))
            c4.metric("Leaves",    personal)
            c5.metric("Lates",     lates)
            c6.metric("Anomalies", 0 if my_ano.empty else len(my_ano))

            wknd_hrs = float(base[pd.to_datetime(base["Date"]).dt.weekday >= 5]["Hours"].sum())
            if wknd_hrs > 0:
                st.caption(
                    f"🗓️ Includes {_fmt_hrs(wknd_hrs)} worked on weekends — counted "
                    "toward Hours, while Expected stays based on weekdays."
                )

            # Weekly trend — only meaningful when the range spans 2+ weeks
            wk_dates = pd.to_datetime(ddf["Date"]).dt.date
            weekly = (
                pd.DataFrame({
                    "Week": [(d - timedelta(days=d.weekday())).isoformat() for d in wk_dates],
                    "Hours": ddf["Hours"].values,
                })
                .groupby("Week")["Hours"].sum().reset_index().sort_values("Week")
            )
            if len(weekly) > 1:
                st.markdown("**Weekly hours**")
                st.bar_chart(weekly.set_index("Week")["Hours"], color="#3b82f6", height=220)
                st.caption(
                    f"Weekly target ≈ {_fmt_hrs(float(emp_row['daily_target_hrs']) * 5)} "
                    "before leave adjustments. The newest week may be partial."
                )

            st.markdown("**Daily log**")
            styled = (
                ddf.style
                .map(_color_hours,   subset=["Hours"])
                .map(_color_deficit, subset=["Break Hrs"])
                .format({"Hours": _fmt_hrs, "Break Hrs": _fmt_hrs})
            )
            st.dataframe(styled, use_container_width=True, hide_index=True)
            _csv_button(ddf, f"{emp_row['display_name']}_{start_str}_to_{end_str}.csv", key="emp_csv")

            if not my_ano.empty:
                st.markdown("**Anomalies in range**")
                st.dataframe(
                    my_ano[["Date", "Type", "Detail"]].style.map(_color_anomaly, subset=["Type"]),
                    use_container_width=True, hide_index=True,
                )


# ── Tab 5: Leaves ─────────────────────────────────────────────────────────────

with tab5:
    start_str, end_str, _gran = range_picker("lv")
    st.markdown("---")

    lv = load_leave_rows(start_str, end_str)
    if lv.empty:
        st.info("No leave records in the selected date range.")
    else:
        personal_lv = lv[~lv["leave_type"].isin(HOLIDAY_LEAVE_TYPES)]
        holidays_n  = int(lv["leave_type"].isin(HOLIDAY_LEAVE_TYPES).sum())

        pivot = (
            pd.crosstab(personal_lv["Employee"], personal_lv["leave_type"])
            if not personal_lv.empty else pd.DataFrame()
        )

        # Include employees active in the range who took no leave — zeros are
        # part of the picture.
        roster_all = load_employees()
        if not roster_all.empty:
            s_d, e_d = date.fromisoformat(start_str), date.fromisoformat(end_str)
            in_range = {
                r["display_name"]
                for _, r in roster_all.iterrows()
                if not r["is_excluded"]
                and (r["_joined"] is None or r["_joined"] <= e_d)
                and (r["_departed"] is None or r["_departed"] >= s_d)
            }
            pivot = pivot.reindex(sorted(in_range | set(pivot.index)))
        pivot = pivot.fillna(0).astype(int)
        pivot["Total"] = pivot.sum(axis=1)
        out = pivot.sort_values("Total", ascending=False).reset_index()
        out = out.rename(columns={out.columns[0]: "Employee"})

        c1, c2, c3 = st.columns(3)
        c1.metric("Personal leave days",       int(out["Total"].sum()))
        c2.metric("Employees with leave",      int((out["Total"] > 0).sum()))
        c3.metric("Public-holiday person-days", holidays_n)

        st.markdown("&nbsp;", unsafe_allow_html=True)
        st.dataframe(out, use_container_width=True, hide_index=True)
        st.caption("Counts are personal leave only — public holidays are excluded (shown in the metric above).")
        _csv_button(out, f"leaves_{start_str}_to_{end_str}.csv", key="lv_csv")
