"""
Attendance Dashboard — Streamlit web app.
Run: streamlit run dashboard.py
"""

import calendar
import os
from datetime import date, timedelta

import pandas as pd
import streamlit as st
from dotenv import load_dotenv
from supabase import create_client

load_dotenv()


def _secret(key: str) -> str:
    try:
        return st.secrets[key]
    except (KeyError, FileNotFoundError):
        return os.environ[key]


st.set_page_config(
    page_title="Attendance Dashboard",
    page_icon="📋",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

st.markdown("""
<style>
footer { visibility: hidden; }

/* Hide sidebar entirely */
section[data-testid="stSidebar"]          { display: none !important; }
button[data-testid="collapsedControl"]    { display: none !important; }
button[data-testid="baseButton-headerNoPadding"] { display: none !important; }

/* Metric cards */
[data-testid="metric-container"] {
    background: rgba(255,255,255,0.06);
    border-radius: 10px;
    border: 1px solid rgba(255,255,255,0.12);
    padding: 1rem 1.25rem;
}
[data-testid="stMetricLabel"] {
    font-size: 0.78rem !important;
    font-weight: 600 !important;
    text-transform: uppercase;
    letter-spacing: .05em;
    opacity: 0.7;
}

/* Tabs */
.stTabs [data-baseweb="tab-list"] {
    background: transparent;
    border-bottom: 2px solid rgba(255,255,255,0.12);
    gap: 0;
    padding-bottom: 0;
}
.stTabs [data-baseweb="tab"] {
    padding: 10px 28px;
    font-size: 0.9rem;
    font-weight: 500;
    border-bottom: 3px solid transparent;
    margin-bottom: -2px;
    background: transparent !important;
}
.stTabs [aria-selected="true"] {
    border-bottom: 3px solid #60a5fa !important;
    font-weight: 700 !important;
}
.stTabs [data-baseweb="tab-highlight"] { display: none !important; }

/* Alert banners */
.alert {
    border-radius: 8px;
    padding: 10px 16px;
    margin-bottom: 8px;
    font-size: 0.88rem;
    font-weight: 500;
    line-height: 1.5;
}
.alert-red    { background: rgba(239,68,68,0.15);  border-left: 4px solid #f87171; color: #fca5a5; }
.alert-yellow { background: rgba(245,158,11,0.15); border-left: 4px solid #fbbf24; color: #fcd34d; }
.alert-blue   { background: rgba(96,165,250,0.15); border-left: 4px solid #60a5fa; color: #93c5fd; }
.alert-green  { background: rgba(34,197,94,0.15);  border-left: 4px solid #4ade80; color: #86efac; }

/* Date badge */
.date-badge {
    display: inline-block;
    background: rgba(96,165,250,0.15);
    border: 1px solid rgba(96,165,250,0.3);
    border-radius: 6px;
    padding: 4px 12px;
    font-size: 0.82rem;
    color: #93c5fd;
    font-weight: 600;
}

/* Prev / Next nav buttons — compact */
.nav-row button {
    padding: 4px 14px !important;
    font-size: 0.82rem !important;
}

/* Segmented control full width */
[data-testid="stSegmentedControl"] { width: 100%; }
[data-testid="stSegmentedControl"] > div { flex-wrap: wrap; gap: 4px; }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# Supabase client
# ---------------------------------------------------------------------------

@st.cache_resource
def get_supabase():
    return create_client(_secret("SUPABASE_URL"), _secret("SUPABASE_SERVICE_KEY"))

sb = get_supabase()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PRESETS = ["Today", "Yesterday", "This Week", "Last Week", "This Month", "Last Month", "Custom"]

ANOMALY_SEVERITY = {
    "Unexcused Absence":    1,
    "Consecutive Absence":  2,
    "Weekly Deficit":       3,
    "Chronic Late Starter": 4,
    "Missing Clock-Out":    5,
    "Late / No Start":      6,
    "Long Breaks":          7,
    "Excessive Hours":      8,
}
_CRITICAL = {"Unexcused Absence", "Consecutive Absence", "Weekly Deficit"}
_WARNING  = {"Chronic Late Starter", "Missing Clock-Out", "Late / No Start"}

# Anomaly types no longer generated by the engine.  Historical rows of these
# types are filtered out of the dashboard so they don't distract managers.
HIDDEN_ANOMALY_TYPES = {"Excessive Breaks", "Early Departure"}

# ---------------------------------------------------------------------------
# Range helpers
# ---------------------------------------------------------------------------

def _compute_range(option: str, offset: int, today: date) -> tuple[date, date, str]:
    """Return (start, end, granularity) for a preset + integer offset."""
    if option in ("Today", "Yesterday"):
        base = today if option == "Today" else today - timedelta(days=1)
        d = min(base + timedelta(days=offset), today)
        return d, d, "day"

    if option in ("This Week", "Last Week"):
        this_monday = today - timedelta(days=today.weekday())
        base_monday = this_monday if option == "This Week" else this_monday - timedelta(days=7)
        monday = base_monday + timedelta(weeks=offset)
        friday = monday + timedelta(days=4)
        return monday, min(friday, today), "week"

    if option in ("This Month", "Last Month"):
        if option == "Last Month":
            first_this = date(today.year, today.month, 1)
            prev       = first_this - timedelta(days=1)
            base_year, base_month = prev.year, prev.month
        else:
            base_year, base_month = today.year, today.month
        total = base_year * 12 + (base_month - 1) + offset
        year  = total // 12
        month = total % 12 + 1
        start = date(year, month, 1)
        last_day = calendar.monthrange(year, month)[1]
        return start, min(date(year, month, last_day), today), "month"

    return today, today, "day"


def _range_label(start: date, end: date, gran: str) -> str:
    if gran == "day":
        return start.strftime("%A, %d %b %Y")
    if gran == "week":
        return f"Week of {start.strftime('%d %b')} – {end.strftime('%d %b %Y')}"
    if start.month == end.month and start.year == end.year:
        return start.strftime("%B %Y")
    return f"{start.strftime('%d %b %Y')} – {end.strftime('%d %b %Y')}"


def _date_badge(start: str, end: str) -> str:
    return f'<span class="date-badge">📅 {start} → {end}</span>'


# ---------------------------------------------------------------------------
# Range picker widget  (one instance per tab, keyed by prefix)
# ---------------------------------------------------------------------------

def range_picker(prefix: str) -> tuple[str, str, str]:
    """
    Renders: segmented control → [◀  date badge  ▶] or custom date pickers.
    Returns (start_str, end_str, granularity) where granularity ∈ {day, week, month}.
    """
    today = date.today()

    seg_key  = f"{prefix}_seg"
    off_key  = f"{prefix}_off"
    prev_key = f"{prefix}_prev_opt"

    # Initialise session state on first render
    if seg_key not in st.session_state:
        st.session_state[seg_key]  = "This Week"
        st.session_state[off_key]  = 0
        st.session_state[prev_key] = "This Week"

    # Segmented control — value lives in st.session_state[seg_key]
    st.segmented_control(
        "Date range",
        PRESETS,
        key=seg_key,
        label_visibility="collapsed",
    )
    option = st.session_state[seg_key]

    # Reset offset whenever user switches to a different preset
    if option != st.session_state[prev_key]:
        st.session_state[off_key]  = 0
        st.session_state[prev_key] = option

    # ── Custom ───────────────────────────────────────────────────────────────
    if option == "Custom":
        c1, c2 = st.columns(2)
        cs = c1.date_input("From", value=today - timedelta(days=30), max_value=today, key=f"{prefix}_cs")
        ce = c2.date_input("To",   value=today - timedelta(days=1),  max_value=today, key=f"{prefix}_ce")
        if cs > ce:
            st.error("'From' must be before 'To'.")
            st.stop()
        gran = "day" if cs == ce else "month"
        return cs.isoformat(), ce.isoformat(), gran

    # ── Preset with Prev / Next ───────────────────────────────────────────────
    offset          = st.session_state[off_key]
    start, end, gran = _compute_range(option, offset, today)
    can_next        = end < today

    prev_col, badge_col, next_col = st.columns([1, 10, 1])

    with prev_col:
        if st.button("◀", key=f"{prefix}_prev", use_container_width=True):
            st.session_state[off_key] -= 1
            st.rerun()

    with badge_col:
        label = _range_label(start, end, gran)
        st.markdown(
            f'<div style="text-align:center;padding:6px 0 2px;">'
            f'{_date_badge(start.isoformat(), end.isoformat())}'
            f'<br><span style="font-size:0.75rem;opacity:0.55;">{label}</span>'
            f'</div>',
            unsafe_allow_html=True,
        )

    with next_col:
        if st.button("▶", key=f"{prefix}_next", use_container_width=True, disabled=not can_next):
            st.session_state[off_key] += 1
            st.rerun()

    return start.isoformat(), end.isoformat(), gran


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _flatten_employees(df: pd.DataFrame):
    emp = pd.json_normalize(df["employees"])
    df  = df.drop(columns=["employees"])
    df["Employee"] = emp["jibble_name"]
    df["Type"]     = emp["employment_type"].str.replace("_", " ").str.title()
    return df, emp


def _parse_date(val):
    """Parse a Supabase date value to a python date object, or None."""
    if val is None:
        return None
    try:
        if pd.isna(val):
            return None
    except (TypeError, ValueError):
        pass
    try:
        return date.fromisoformat(str(val)[:10])
    except (ValueError, TypeError):
        return None


def _filter_active_on(df: pd.DataFrame, snap_date_col: str = "snapshot_date") -> pd.DataFrame:
    """
    Drop rows where the snapshot_date is outside the employee's
    [joined_date, departed_date] active range.  Caller must have already
    flattened employees() and have _joined / _departed columns.
    """
    if df.empty or "_joined" not in df.columns:
        return df
    snap_dates = pd.to_datetime(df[snap_date_col]).dt.date
    join_ok    = df["_joined"].isna()    | (snap_dates >= df["_joined"])
    depart_ok  = df["_departed"].isna()  | (snap_dates <= df["_departed"])
    return df[join_ok & depart_ok].copy()


def _working_days_active(monday: date, friday: date, joined, departed) -> int:
    """Count Mon-Fri days in [monday, friday] within the employee's active range."""
    return sum(
        1 for i in range(5)
        if (joined is None or monday + timedelta(days=i) >= joined)
        and (departed is None or monday + timedelta(days=i) <= departed)
    )


def _fmt_hrs(h) -> str:
    try:
        h = float(h)
    except (TypeError, ValueError):
        return "—"
    if pd.isna(h):
        return "—"
    total_min = round(abs(h) * 60)
    return f"{total_min // 60}h {total_min % 60}m"


def _parse_utc(val) -> "pd.Timestamp":
    """Parse a raw Supabase timestamptz value to a UTC-aware Timestamp, or NaT.

    Using the scalar pd.to_datetime path is intentional: the vectorised
    pd.to_datetime(series, utc=True) can silently coerce valid timezone-aware
    strings to NaT on some pandas builds when the column contains a mix of
    timezone-aware strings and None values.
    """
    if val is None:
        return pd.NaT
    try:
        if pd.isna(val):
            return pd.NaT
    except (TypeError, ValueError):
        pass
    return pd.to_datetime(val, utc=True, errors="coerce")


def _to_ist_str(val) -> str:
    """Convert a raw timestamptz value to an IST HH:MM AM/PM string, or '—'."""
    ts = _parse_utc(val)
    if pd.isna(ts):
        return "—"
    return ts.tz_convert("Asia/Kolkata").strftime("%I:%M %p")


def _csv_button(df: pd.DataFrame, filename: str, key: str):
    """Render a 'Export CSV' download button for the given DataFrame."""
    if df is None or df.empty:
        return
    csv = df.to_csv(index=False).encode("utf-8")
    st.download_button(
        "📥 Export CSV",
        data=csv,
        file_name=filename,
        mime="text/csv",
        key=key,
    )


# ---------------------------------------------------------------------------
# Data loaders
# ---------------------------------------------------------------------------

@st.cache_data(ttl=60)
def load_last_synced() -> str | None:
    """Most-recent engine run time (global max pulled_at across all snapshot dates).
    Shown once in the page header so every view — Today, Yesterday, Week, etc. —
    displays the same consistent sync timestamp.
    """
    res = (
        sb.table("daily_snapshots")
        .select("pulled_at")
        .order("pulled_at", desc=True)
        .limit(1)
        .execute()
    )
    if not res.data:
        return None
    ts = _parse_utc(res.data[0].get("pulled_at"))
    return ts.tz_convert("Asia/Kolkata").strftime("%-I:%M %p") if pd.notna(ts) else None


@st.cache_data(ttl=60)
def load_daily_snapshot(snap_date: str) -> pd.DataFrame:
    """Returns formatted attendance DataFrame for snap_date."""
    rows = (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, session_count, first_clock_in, last_clock_out, leave_type, pulled_at, "
                "employees(jibble_name, employment_type, joined_date, departed_date)")
        .eq("snapshot_date", snap_date)
        .execute()
    )
    df = pd.DataFrame(rows.data)
    if df.empty:
        return df

    df, emp_raw = _flatten_employees(df)
    df["_joined"]   = emp_raw["joined_date"].map(_parse_date)
    df["_departed"] = emp_raw["departed_date"].map(_parse_date)
    df = _filter_active_on(df)
    df = df.drop(columns=["_joined", "_departed"])
    if df.empty:
        return df

    # Parse timestamps element-by-element via the scalar path.
    # pd.to_datetime(series, utc=True) can silently coerce valid timezone-aware
    # strings to NaT when the column also contains None values on some pandas
    # versions, so we map the scalar helper across the column instead.
    first_ts = df["first_clock_in"].map(_parse_utc)   # object Series: Timestamps + NaT
    last_ts  = df["last_clock_out"].map(_parse_utc)

    # Break Hrs: span(clock-out − clock-in) minus worked hours
    def _span(fi, lo):
        if pd.isna(fi) or pd.isna(lo):
            return float("nan")
        return (lo - fi).total_seconds() / 3600

    span_hrs = pd.Series(
        [_span(fi, lo) for fi, lo in zip(first_ts, last_ts)], index=df.index
    )
    df["Break Hrs"] = (span_hrs - df["hours_logged"].astype(float)).clip(lower=0).round(2)

    df["first_clock_in"] = first_ts.map(_to_ist_str)
    df["last_clock_out"]  = last_ts.map(_to_ist_str)
    df["leave_type"]      = df["leave_type"].fillna("")

    df = df.rename(columns={
        "hours_logged":   "Total Hours",
        "session_count":  "Sessions",
        "first_clock_in": "Clock In",
        "last_clock_out": "Clock Out",
        "leave_type":     "Leave",
    })
    df = df.sort_values(["Total Hours", "Employee"]).drop(columns=["snapshot_date", "pulled_at"])
    # Leave moved to col 3 so it's always visible
    return df[["Employee", "Type", "Leave", "Total Hours", "Break Hrs", "Sessions", "Clock In", "Clock Out"]].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_weekly_summary(week_start: str, week_end: str) -> pd.DataFrame:
    """
    Compute weekly summary LIVE from daily_snapshots — never reads the cached
    weekly_summaries table, so retroactive leave approvals are reflected the
    moment the engine re-syncs those days regardless of how old the week is.
    Targets are pro-rated by each employee's active range so joiners /
    departures within the week are handled correctly.
    """
    rows = (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, leave_type, "
                "employees(jibble_name, employment_type, weekly_target_hrs, daily_target_hrs, joined_date, departed_date)")
        .gte("snapshot_date", week_start)
        .lte("snapshot_date", week_end)
        .execute()
    )
    df = pd.DataFrame(rows.data)
    if df.empty:
        return df

    emp_cols = pd.json_normalize(df["employees"])
    df = df.drop(columns=["employees"])
    df["Employee"]       = emp_cols["jibble_name"]
    df["weekly_target"]  = emp_cols["weekly_target_hrs"].astype(float)
    df["daily_target"]   = emp_cols["daily_target_hrs"].astype(float)
    df["_joined"]        = emp_cols["joined_date"].map(_parse_date)
    df["_departed"]      = emp_cols["departed_date"].map(_parse_date)
    df["leave_type"]     = df["leave_type"].fillna("")
    df["hours_logged"]   = df["hours_logged"].astype(float)

    # Drop snapshot rows outside each employee's active range
    df = _filter_active_on(df)
    if df.empty:
        return df

    monday = date.fromisoformat(week_start)
    friday = date.fromisoformat(week_end)

    agg = (
        df.groupby("Employee")
        .agg(
            Hours        = ("hours_logged", "sum"),
            Leave_Days   = ("leave_type",   lambda x: (x != "").sum()),
            weekly_target= ("weekly_target", "first"),
            daily_target = ("daily_target",  "first"),
            _joined      = ("_joined",       "first"),
            _departed    = ("_departed",     "first"),
        )
        .reset_index()
    )

    # Pro-rated target: working days within active range × daily_target,
    # minus leave days within that window.
    agg["active_days"] = agg.apply(
        lambda r: _working_days_active(monday, friday, r["_joined"], r["_departed"]),
        axis=1,
    )
    agg = agg[agg["active_days"] > 0]   # drop employees with no overlap
    agg["Target"]  = ((agg["active_days"] - agg["Leave_Days"]) * agg["daily_target"]).clip(lower=0).round(2)
    agg["Deficit"] = (agg["Target"] - agg["Hours"]).clip(lower=0).round(2)

    def _status(row):
        if row["Hours"] >= row["Target"]:     return "Met"
        if row["Hours"] >= row["Target"] - 4: return "At Risk"
        return "Deficit"

    agg["Status"] = agg.apply(_status, axis=1)
    order = {"Deficit": 0, "At Risk": 1, "Met": 2}
    agg = agg.sort_values("Status", key=lambda s: s.map(order))
    agg = agg.rename(columns={"Leave_Days": "Leave Days"})
    return agg[["Employee", "Status", "Hours", "Target", "Deficit", "Leave Days"]].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_current_week(monday: str, through: str) -> pd.DataFrame:
    if monday > through:
        return pd.DataFrame()

    rows = (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, leave_type, "
                "employees(jibble_name, employment_type, weekly_target_hrs, daily_target_hrs, joined_date, departed_date)")
        .gte("snapshot_date", monday)
        .lte("snapshot_date", through)
        .execute()
    )
    df = pd.DataFrame(rows.data)
    if df.empty:
        return df

    emp_cols = pd.json_normalize(df["employees"])
    df = df.drop(columns=["employees"])
    df["Employee"]      = emp_cols["jibble_name"]
    df["weekly_target"] = emp_cols["weekly_target_hrs"].astype(float)
    df["daily_target"]  = emp_cols["daily_target_hrs"].astype(float)
    df["_joined"]       = emp_cols["joined_date"].map(_parse_date)
    df["_departed"]     = emp_cols["departed_date"].map(_parse_date)
    df["leave_type"]    = df["leave_type"].fillna("")

    df = _filter_active_on(df)
    if df.empty:
        return df

    monday_date   = date.fromisoformat(monday)
    friday_date   = monday_date + timedelta(days=4)
    today         = date.today()
    days_elapsed  = sum(
        1 for i in range((today - monday_date).days + 1)
        if (monday_date + timedelta(days=i)).weekday() < 5
    )
    days_elapsed = max(days_elapsed, 1)

    agg = (
        df.groupby("Employee")
        .agg(
            Hours        = ("hours_logged", "sum"),
            Leave_Days   = ("leave_type",   lambda x: (x != "").sum()),
            weekly_target= ("weekly_target", "first"),
            daily_target = ("daily_target",  "first"),
            _joined      = ("_joined",       "first"),
            _departed    = ("_departed",     "first"),
        )
        .reset_index()
    )

    # Pro-rated target uses active working days within Mon-Fri
    agg["active_days"] = agg.apply(
        lambda r: _working_days_active(monday_date, friday_date, r["_joined"], r["_departed"]),
        axis=1,
    )
    agg = agg[agg["active_days"] > 0]
    agg["Target"]    = ((agg["active_days"] - agg["Leave_Days"]) * agg["daily_target"]).clip(lower=0)
    agg["Projected"] = (agg["Hours"] / days_elapsed * 5).round(2)
    agg["Days Left"] = max(5 - days_elapsed, 0)

    def _status(row):
        if row["Projected"] >= row["Target"]:     return "On Track"
        if row["Projected"] >= row["Target"] - 4: return "At Risk"
        return "Deficit"

    agg["Status"] = agg.apply(_status, axis=1)
    order = {"Deficit": 0, "At Risk": 1, "On Track": 2}
    agg = agg.sort_values("Status", key=lambda s: s.map(order))
    agg = agg.rename(columns={"Leave_Days": "Leave Days"})
    # Status first
    return agg[["Employee", "Status", "Hours", "Target", "Projected", "Leave Days", "Days Left"]].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_monthly_summary(start: str, end: str) -> pd.DataFrame:
    rows = (
        sb.table("daily_snapshots")
        .select("snapshot_date, hours_logged, leave_type, "
                "employees(jibble_name, employment_type, weekly_target_hrs, daily_target_hrs, joined_date, departed_date)")
        .gte("snapshot_date", start)
        .lte("snapshot_date", end)
        .execute()
    )
    df = pd.DataFrame(rows.data)
    if df.empty:
        return df

    emp_cols = pd.json_normalize(df["employees"])
    df = df.drop(columns=["employees"])
    df["Employee"]     = emp_cols["jibble_name"]
    df["daily_target"] = emp_cols["daily_target_hrs"].astype(float)
    df["_joined"]      = emp_cols["joined_date"].map(_parse_date)
    df["_departed"]    = emp_cols["departed_date"].map(_parse_date)
    df["leave_type"]   = df["leave_type"].fillna("")
    df["hours_logged"] = df["hours_logged"].astype(float)

    # Drop snapshot rows outside each employee's active range
    df = _filter_active_on(df)
    if df.empty:
        return df

    # Compute Expected Hrs per-employee as (working_days in active range ∩ [start,end] − leave_days) × daily_target.
    start_d = date.fromisoformat(start)
    end_d   = date.fromisoformat(end)

    def _working_days_in_range(joined, departed) -> int:
        """Count Mon-Fri days in [start_d, end_d] within employee's active range."""
        lo = max(start_d, joined)   if joined   else start_d
        hi = min(end_d,   departed) if departed else end_d
        if hi < lo:
            return 0
        return sum(
            1 for i in range((hi - lo).days + 1)
            if (lo + timedelta(days=i)).weekday() < 5
        )

    agg = (
        df.groupby("Employee")
        .agg(
            Total_Hours  = ("hours_logged", "sum"),
            Days_Present = ("hours_logged", lambda x: (x > 0).sum()),
            Days_Absent  = ("hours_logged", lambda x: ((x == 0) & (df.loc[x.index, "leave_type"] == "")).sum()),
            Leave_Days   = ("leave_type",   lambda x: (x != "").sum()),
            daily_target = ("daily_target", "first"),
            _joined      = ("_joined",       "first"),
            _departed    = ("_departed",     "first"),
        )
        .reset_index()
    )
    agg["working_days"] = agg.apply(
        lambda r: _working_days_in_range(r["_joined"], r["_departed"]), axis=1
    )
    agg = agg[agg["working_days"] > 0]
    agg["Expected Hrs"] = ((agg["working_days"] - agg["Leave_Days"]) * agg["daily_target"]).clip(lower=0).round(2)
    agg["Deficit"]      = (agg["Expected Hrs"] - agg["Total_Hours"]).clip(lower=0).round(2)
    agg = agg.sort_values("Deficit", ascending=False)
    agg = agg.rename(columns={
        "Total_Hours": "Hours", "Days_Present": "Days Present",
        "Days_Absent": "Days Absent", "Leave_Days": "Leave Days",
    })
    return agg[["Employee", "Deficit", "Hours", "Expected Hrs", "Days Present", "Days Absent", "Leave Days"]].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_anomalies(start: str, end: str) -> pd.DataFrame:
    rows = (
        sb.table("anomalies")
        .select("anomaly_date, anomaly_type, detail, employees(jibble_name, joined_date, departed_date)")
        .gte("anomaly_date", start)
        .lte("anomaly_date", end)
        .order("anomaly_date", desc=True)
        .limit(1000)
        .execute()
    )
    df = pd.DataFrame(rows.data)
    if df.empty:
        return df

    emp = pd.json_normalize(df["employees"])
    df  = df.drop(columns=["employees"])
    df["Employee"]  = emp["jibble_name"]
    df["_joined"]   = emp["joined_date"].map(_parse_date)
    df["_departed"] = emp["departed_date"].map(_parse_date)
    df = df.rename(columns={"anomaly_date": "Date", "anomaly_type": "Type", "detail": "Detail"})

    # Hide deprecated anomaly types (Excessive Breaks, Early Departure) — they
    # are no longer generated but historical rows still exist.
    df = df[~df["Type"].isin(HIDDEN_ANOMALY_TYPES)]
    # Hide anomalies outside the employee's active range (e.g. stale Absence
    # flags for someone who'd already left or hadn't joined yet)
    df = _filter_active_on(df, snap_date_col="Date")
    df = df.drop(columns=["_joined", "_departed"])
    if df.empty:
        return df
    df["_sev"] = df["Type"].map(ANOMALY_SEVERITY).fillna(99)
    df = df.sort_values(["_sev", "Date"], ascending=[True, False]).drop(columns=["_sev"])
    return df[["Date", "Employee", "Type", "Detail"]].reset_index(drop=True)


@st.cache_data(ttl=60)
def load_anomaly_summary(start: str, end: str) -> pd.DataFrame:
    df = load_anomalies(start, end)
    if df.empty:
        return df

    type_cols = sorted(ANOMALY_SEVERITY, key=ANOMALY_SEVERITY.get)
    records = []
    for emp, grp in df.groupby("Employee"):
        row = {"Employee": emp, "Total": len(grp)}
        for t in type_cols:
            row[t] = int((grp["Type"] == t).sum())
        records.append(row)
    return pd.DataFrame(records).sort_values("Total", ascending=False).reset_index(drop=True)


# ---------------------------------------------------------------------------
# Stylers
# ---------------------------------------------------------------------------

def _color_status(val):
    return {
        "Met":      "color:#4ade80; font-weight:700",
        "On Track": "color:#4ade80; font-weight:700",
        "At Risk":  "color:#fbbf24; font-weight:700",
        "Deficit":  "color:#f87171; font-weight:700",
    }.get(val, "")

def _color_anomaly(val):
    if val in _CRITICAL: return "color:#f87171; font-weight:700"
    if val in _WARNING:  return "color:#fbbf24; font-weight:600"
    return "color:#60a5fa; font-weight:600"

def _color_hours(val):
    try:
        h = float(val)
    except (TypeError, ValueError):
        return ""
    if h == 0:  return "color:#f87171; font-weight:700"
    if h < 4:   return "color:#fbbf24; font-weight:600"
    if h >= 10: return "color:#60a5fa; font-weight:600"
    return ""  # normal range — use theme default so it's readable on both light and dark

def _color_deficit(val):
    try:
        h = float(val)
    except (TypeError, ValueError):
        return ""
    if h > 4: return "color:#f87171; font-weight:700"
    if h > 0: return "color:#fbbf24; font-weight:600"
    return "color:#4ade80; font-weight:600"

def _color_absent(val):
    try:
        v = int(val)
    except (TypeError, ValueError):
        return ""
    if v == 0: return "color:#4ade80"
    if v <= 2: return "color:#fbbf24; font-weight:600"
    return "color:#f87171; font-weight:700"

def _heat_count(val):
    try:
        v = int(val)
    except (TypeError, ValueError):
        return ""
    if v == 0: return "color:#475569"
    if v == 1: return "color:#fbbf24; font-weight:600"
    return "color:#f87171; font-weight:700"


# ---------------------------------------------------------------------------
# Page header
# ---------------------------------------------------------------------------

_hdr_col, _sync_col, _ref_col = st.columns([5, 2, 1])
_hdr_col.markdown("## 📋 Attendance Dashboard")
_last_synced_global = load_last_synced()
if _last_synced_global:
    _sync_col.markdown(
        f'<div style="text-align:right;padding-top:14px;font-size:0.78rem;opacity:0.65;">'
        f'⏱ Engine last synced: <b>{_last_synced_global} IST</b></div>',
        unsafe_allow_html=True,
    )
if _ref_col.button("🔄", key="global_refresh", help="Refresh all data"):
    load_daily_snapshot.clear()
    load_last_synced.clear()
    load_weekly_summary.clear()
    load_current_week.clear()
    load_monthly_summary.clear()
    load_anomalies.clear()
    load_anomaly_summary.clear()
    st.rerun()
st.markdown("---")

# ---------------------------------------------------------------------------
# Tabs
# ---------------------------------------------------------------------------

tab1, tab2, tab3 = st.tabs(["Attendance", "Anomalies", "Anomaly Breakdown"])


# ── Tab 1: Attendance ─────────────────────────────────────────────────────────

with tab1:
    today = date.today()
    start_str, end_str, gran = range_picker("att")
    start = date.fromisoformat(start_str)
    end   = date.fromisoformat(end_str)

    st.markdown("---")

    # ── Day view ─────────────────────────────────────────────────────────────
    if gran == "day":
        df = load_daily_snapshot(start_str)
        if df.empty:
            st.info(f"No snapshot data for {start.strftime('%A, %d %b %Y')}. The engine may not have run yet.")
        else:
            absent   = df[(df["Total Hours"] == 0) & (df["Leave"] == "")]
            low_hrs  = df[(df["Total Hours"] > 0) & (df["Total Hours"] < 4) & (df["Leave"] == "")]
            on_leave = df[df["Leave"] != ""]

            if not absent.empty:
                names = ", ".join(absent["Employee"].tolist())
                st.markdown(f'<div class="alert alert-red">🔴 <b>Absent, no leave ({len(absent)}):</b> {names}</div>', unsafe_allow_html=True)
            if not low_hrs.empty:
                names = ", ".join(low_hrs["Employee"].tolist())
                st.markdown(f'<div class="alert alert-yellow">⚠️ <b>Under 4h logged ({len(low_hrs)}):</b> {names}</div>', unsafe_allow_html=True)
            if not on_leave.empty:
                names = ", ".join(on_leave["Employee"].tolist())
                st.markdown(f'<div class="alert alert-blue">🔵 <b>On leave ({len(on_leave)}):</b> {names}</div>', unsafe_allow_html=True)
            if absent.empty and low_hrs.empty:
                st.markdown('<div class="alert alert-green">✅ No attendance issues.</div>', unsafe_allow_html=True)

            c1, c2, c3, c4, c5 = st.columns(5)
            c1.metric("Present",    int((df["Total Hours"] > 0).sum()))
            c2.metric("Absent",     len(absent))
            c3.metric("On Leave",   len(on_leave))
            present_hrs = df[df["Total Hours"] > 0]["Total Hours"]
            c4.metric("Avg Hours",  _fmt_hrs(present_hrs.mean() if not present_hrs.empty else 0))
            c5.metric("Avg Breaks", _fmt_hrs(df["Break Hrs"].mean()))

            st.markdown("&nbsp;", unsafe_allow_html=True)
            styled = (
                df.style
                .map(_color_hours, subset=["Total Hours"])
                .map(_color_deficit, subset=["Break Hrs"])
                .format({"Total Hours": _fmt_hrs, "Break Hrs": _fmt_hrs})
            )
            st.dataframe(styled, use_container_width=True, hide_index=True)
            _csv_button(df, f"attendance_{start_str}.csv", key="att_day_csv")

    # ── Week view ─────────────────────────────────────────────────────────────
    elif gran == "week":
        this_monday      = today - timedelta(days=today.weekday())
        is_current_week  = (start == this_monday)

        if is_current_week:
            through = min(end, today).isoformat()
            df = load_current_week(start_str, through)
            if df.empty:
                st.info("No data yet for this week.")
            else:
                days_elapsed = sum(
                    1 for i in range((today - start).days + 1)
                    if (start + timedelta(days=i)).weekday() < 5
                )
                st.markdown(
                    f"**Week of {start.strftime('%d %b %Y')}** · "
                    f"{days_elapsed} working day(s) elapsed · Live projection"
                )

                deficit_emp = df[df["Status"] == "Deficit"]
                at_risk_emp = df[df["Status"] == "At Risk"]
                if not deficit_emp.empty:
                    names = ", ".join(deficit_emp["Employee"].tolist())
                    st.markdown(f'<div class="alert alert-red">🔴 <b>Projected deficit ({len(deficit_emp)}):</b> {names}</div>', unsafe_allow_html=True)
                if not at_risk_emp.empty:
                    names = ", ".join(at_risk_emp["Employee"].tolist())
                    st.markdown(f'<div class="alert alert-yellow">⚠️ <b>At risk ({len(at_risk_emp)}):</b> {names}</div>', unsafe_allow_html=True)
                if deficit_emp.empty and at_risk_emp.empty:
                    st.markdown('<div class="alert alert-green">✅ Everyone is on track this week.</div>', unsafe_allow_html=True)

                c1, c2, c3 = st.columns(3)
                c1.metric("On Track", int((df["Status"] == "On Track").sum()))
                c2.metric("At Risk",  int((df["Status"] == "At Risk").sum()))
                c3.metric("Deficit",  int((df["Status"] == "Deficit").sum()))

                st.markdown("&nbsp;", unsafe_allow_html=True)
                styled = (
                    df.style
                    .map(_color_status, subset=["Status"])
                    .format({"Hours": _fmt_hrs, "Target": _fmt_hrs, "Projected": _fmt_hrs})
                )
                st.dataframe(styled, use_container_width=True, hide_index=True)
                _csv_button(df, f"week_{start_str}.csv", key="att_curweek_csv")

        else:
            df = load_weekly_summary(start_str, end_str)
            if df.empty:
                st.info(
                    f"No snapshot data for the week of {start.strftime('%d %b %Y')}. "
                    "This week may not have been processed yet — try running: "
                    "`python main.py --date " + end_str + "`"
                )
            else:
                deficit_emp = df[df["Status"] == "Deficit"]
                at_risk_emp = df[df["Status"] == "At Risk"]
                if not deficit_emp.empty:
                    names = ", ".join(deficit_emp["Employee"].tolist())
                    st.markdown(f'<div class="alert alert-red">🔴 <b>Deficit ({len(deficit_emp)}):</b> {names}</div>', unsafe_allow_html=True)
                if not at_risk_emp.empty:
                    names = ", ".join(at_risk_emp["Employee"].tolist())
                    st.markdown(f'<div class="alert alert-yellow">⚠️ <b>At risk ({len(at_risk_emp)}):</b> {names}</div>', unsafe_allow_html=True)
                if deficit_emp.empty and at_risk_emp.empty:
                    st.markdown('<div class="alert alert-green">✅ All targets met this week.</div>', unsafe_allow_html=True)

                c1, c2, c3 = st.columns(3)
                c1.metric("Met",     int((df["Status"] == "Met").sum()))
                c2.metric("At Risk", int((df["Status"] == "At Risk").sum()))
                c3.metric("Deficit", int((df["Status"] == "Deficit").sum()))

                st.markdown("&nbsp;", unsafe_allow_html=True)
                styled = (
                    df.style
                    .map(_color_status,  subset=["Status"])
                    .map(_color_deficit, subset=["Deficit"])
                    .format({"Hours": _fmt_hrs, "Target": _fmt_hrs, "Deficit": _fmt_hrs})
                )
                st.dataframe(styled, use_container_width=True, hide_index=True)
                _csv_button(df, f"week_{start_str}.csv", key="att_pastweek_csv")

    # ── Month / range view ────────────────────────────────────────────────────
    else:
        df = load_monthly_summary(start_str, end_str)
        if df.empty:
            st.info(f"No data for this period.")
        else:
            last_day_of_month = calendar.monthrange(end.year, end.month)[1]
            is_partial = (start.day == 1 and end < date(end.year, end.month, last_day_of_month))
            label      = _range_label(start, end, "month")
            partial_note = (
                f" · ⚠️ Partial — {end.day} of {last_day_of_month} days elapsed"
                if is_partial else ""
            )
            st.markdown(f"**{label}**{partial_note}")

            high_def = df[df["Deficit"] > 8]
            if not high_def.empty:
                names = ", ".join(high_def["Employee"].tolist())
                st.markdown(f'<div class="alert alert-red">🔴 <b>High deficit &gt;8h ({len(high_def)}):</b> {names}</div>', unsafe_allow_html=True)

            c1, c2, c3 = st.columns(3)
            c1.metric("Total Hours",      _fmt_hrs(df["Hours"].sum()))
            c2.metric("Avg per Employee", _fmt_hrs(df["Hours"].mean()))
            c3.metric("Total Deficit",    _fmt_hrs(df["Deficit"].sum()))

            st.markdown("&nbsp;", unsafe_allow_html=True)
            styled = (
                df.style
                .map(_color_deficit, subset=["Deficit"])
                .map(_color_absent,  subset=["Days Absent"])
                .format({"Hours": _fmt_hrs, "Expected Hrs": _fmt_hrs, "Deficit": _fmt_hrs})
            )
            st.dataframe(styled, use_container_width=True, hide_index=True)
            _csv_button(df, f"range_{start_str}_to_{end_str}.csv", key="att_month_csv")


# ── Tab 2: Anomalies ──────────────────────────────────────────────────────────

with tab2:
    start_str, end_str, _ = range_picker("ano")

    df = load_anomalies(start_str, end_str)

    st.markdown("---")

    if df.empty:
        st.info("No anomalies in the selected date range.")
    else:
        col_a, col_b = st.columns(2)
        with col_a:
            types    = ["All"] + sorted(df["Type"].unique().tolist())
            sel_type = st.selectbox("Anomaly type", types)
        with col_b:
            emps    = ["All"] + sorted(df["Employee"].unique().tolist())
            sel_emp = st.selectbox("Employee", emps)

        if sel_type != "All": df = df[df["Type"] == sel_type]
        if sel_emp  != "All": df = df[df["Employee"] == sel_emp]

        n_critical = int(df["Type"].isin(_CRITICAL).sum())
        n_warning  = int(df["Type"].isin(_WARNING).sum())
        n_info     = len(df) - n_critical - n_warning

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Total",    len(df))
        c2.metric("Critical", n_critical)
        c3.metric("Warning",  n_warning)
        c4.metric("Info",     n_info)

        st.markdown("&nbsp;", unsafe_allow_html=True)
        st.caption("Sorted by severity · Critical (red) → Warning (amber) → Info (blue)")
        styled = df.style.map(_color_anomaly, subset=["Type"])
        st.dataframe(styled, use_container_width=True, hide_index=True)
        _csv_button(df, f"anomalies_{start_str}_to_{end_str}.csv", key="ano_csv")


# ── Tab 3: Anomaly Breakdown ──────────────────────────────────────────────────

with tab3:
    start_str, end_str, _ = range_picker("brk")

    df = load_anomaly_summary(start_str, end_str)

    st.markdown("---")

    if df.empty:
        st.info("No anomaly data in the selected date range.")
    else:
        st.markdown("**Breakdown by employee** · sorted by total anomalies")
        st.markdown(
            '<div style="font-size:0.82rem;opacity:0.7;margin-bottom:12px;">'
            '🔵 0 = none &nbsp;·&nbsp; 🟡 1 = amber &nbsp;·&nbsp; 🔴 2+ = red'
            '</div>',
            unsafe_allow_html=True,
        )
        num_cols = [c for c in df.columns if c != "Employee"]
        styled = df.style.map(_heat_count, subset=num_cols)
        st.dataframe(styled, use_container_width=True, hide_index=True)
